/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodFeegrantPeriodV1beta1PeriodQueryAllowancesResponse : QueryAllowancesResponse is the response type for the Query/Allowances RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodFeegrantPeriodV1beta1PeriodQueryAllowancesResponse {
    /// allowances are allowance's granted for grantee by granter.
    #[serde(rename = "allowances", skip_serializing_if = "Option::is_none")]
    pub allowances: Option<Vec<crate::models::CosmosPeriodFeegrantPeriodV1beta1PeriodGrant>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodFeegrantPeriodV1beta1PeriodQueryAllowancesResponse {
    /// QueryAllowancesResponse is the response type for the Query/Allowances RPC method.
    pub fn new() -> CosmosPeriodFeegrantPeriodV1beta1PeriodQueryAllowancesResponse {
        CosmosPeriodFeegrantPeriodV1beta1PeriodQueryAllowancesResponse {
            allowances: None,
            pagination: None,
        }
    }
}


