/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodMsgDescriptor {
    /// msg_type_url contains the TypeURL of a sdk.Msg.
    #[serde(rename = "msgTypeUrl", skip_serializing_if = "Option::is_none")]
    pub msg_type_url: Option<String>,
}

impl CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodMsgDescriptor {
    pub fn new() -> CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodMsgDescriptor {
        CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodMsgDescriptor {
            msg_type_url: None,
        }
    }
}


