/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGroupPeriodV1PeriodQueryProposalsByGroupPolicyResponse : QueryProposalsByGroupPolicyResponse is the Query/ProposalByGroupPolicy response type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGroupPeriodV1PeriodQueryProposalsByGroupPolicyResponse {
    /// proposals are the proposals with given group policy.
    #[serde(rename = "proposals", skip_serializing_if = "Option::is_none")]
    pub proposals: Option<Vec<crate::models::CosmosPeriodGroupPeriodV1PeriodProposal>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodGroupPeriodV1PeriodQueryProposalsByGroupPolicyResponse {
    /// QueryProposalsByGroupPolicyResponse is the Query/ProposalByGroupPolicy response type.
    pub fn new() -> CosmosPeriodGroupPeriodV1PeriodQueryProposalsByGroupPolicyResponse {
        CosmosPeriodGroupPeriodV1PeriodQueryProposalsByGroupPolicyResponse {
            proposals: None,
            pagination: None,
        }
    }
}


