/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodAuthPeriodV1beta1PeriodQueryParamsResponse : QueryParamsResponse is the response type for the Query/Params RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodAuthPeriodV1beta1PeriodQueryParamsResponse {
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Box<crate::models::CosmosPeriodAuthPeriodV1beta1PeriodParams>>,
}

impl CosmosPeriodAuthPeriodV1beta1PeriodQueryParamsResponse {
    /// QueryParamsResponse is the response type for the Query/Params RPC method.
    pub fn new() -> CosmosPeriodAuthPeriodV1beta1PeriodQueryParamsResponse {
        CosmosPeriodAuthPeriodV1beta1PeriodQueryParamsResponse {
            params: None,
        }
    }
}


