/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodQueryMethodDescriptor {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "fullQueryPath", skip_serializing_if = "Option::is_none")]
    pub full_query_path: Option<String>,
}

impl CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodQueryMethodDescriptor {
    pub fn new() -> CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodQueryMethodDescriptor {
        CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodQueryMethodDescriptor {
            name: None,
            full_query_path: None,
        }
    }
}


