/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodQueryServiceDescriptor {
    #[serde(rename = "fullname", skip_serializing_if = "Option::is_none")]
    pub fullname: Option<String>,
    #[serde(rename = "isModule", skip_serializing_if = "Option::is_none")]
    pub is_module: Option<bool>,
    #[serde(rename = "methods", skip_serializing_if = "Option::is_none")]
    pub methods: Option<Vec<crate::models::CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodQueryMethodDescriptor>>,
}

impl CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodQueryServiceDescriptor {
    pub fn new() -> CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodQueryServiceDescriptor {
        CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodQueryServiceDescriptor {
            fullname: None,
            is_module: None,
            methods: None,
        }
    }
}


