/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodUpgradePeriodV1beta1PeriodQueryAuthorityResponse : Since: cosmos-sdk 0.46



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodUpgradePeriodV1beta1PeriodQueryAuthorityResponse {
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
}

impl CosmosPeriodUpgradePeriodV1beta1PeriodQueryAuthorityResponse {
    /// Since: cosmos-sdk 0.46
    pub fn new() -> CosmosPeriodUpgradePeriodV1beta1PeriodQueryAuthorityResponse {
        CosmosPeriodUpgradePeriodV1beta1PeriodQueryAuthorityResponse {
            address: None,
        }
    }
}


