/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGroupPeriodV1PeriodProposalStatus : ProposalStatus defines proposal statuses.   - PROPOSAL_STATUS_UNSPECIFIED: An empty value is invalid and not allowed.  - PROPOSAL_STATUS_SUBMITTED: Initial status of a proposal when submitted.  - PROPOSAL_STATUS_ACCEPTED: Final status of a proposal when the final tally is done and the outcome passes the group policy's decision policy.  - PROPOSAL_STATUS_REJECTED: Final status of a proposal when the final tally is done and the outcome is rejected by the group policy's decision policy.  - PROPOSAL_STATUS_ABORTED: Final status of a proposal when the group policy is modified before the final tally.  - PROPOSAL_STATUS_WITHDRAWN: A proposal can be withdrawn before the voting start time by the owner. When this happens the final status is Withdrawn.

/// ProposalStatus defines proposal statuses.   - PROPOSAL_STATUS_UNSPECIFIED: An empty value is invalid and not allowed.  - PROPOSAL_STATUS_SUBMITTED: Initial status of a proposal when submitted.  - PROPOSAL_STATUS_ACCEPTED: Final status of a proposal when the final tally is done and the outcome passes the group policy's decision policy.  - PROPOSAL_STATUS_REJECTED: Final status of a proposal when the final tally is done and the outcome is rejected by the group policy's decision policy.  - PROPOSAL_STATUS_ABORTED: Final status of a proposal when the group policy is modified before the final tally.  - PROPOSAL_STATUS_WITHDRAWN: A proposal can be withdrawn before the voting start time by the owner. When this happens the final status is Withdrawn.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CosmosPeriodGroupPeriodV1PeriodProposalStatus {
    #[serde(rename = "PROPOSAL_STATUS_UNSPECIFIED")]
    Unspecified,
    #[serde(rename = "PROPOSAL_STATUS_SUBMITTED")]
    Submitted,
    #[serde(rename = "PROPOSAL_STATUS_ACCEPTED")]
    Accepted,
    #[serde(rename = "PROPOSAL_STATUS_REJECTED")]
    Rejected,
    #[serde(rename = "PROPOSAL_STATUS_ABORTED")]
    Aborted,
    #[serde(rename = "PROPOSAL_STATUS_WITHDRAWN")]
    Withdrawn,

}

impl ToString for CosmosPeriodGroupPeriodV1PeriodProposalStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Unspecified => String::from("PROPOSAL_STATUS_UNSPECIFIED"),
            Self::Submitted => String::from("PROPOSAL_STATUS_SUBMITTED"),
            Self::Accepted => String::from("PROPOSAL_STATUS_ACCEPTED"),
            Self::Rejected => String::from("PROPOSAL_STATUS_REJECTED"),
            Self::Aborted => String::from("PROPOSAL_STATUS_ABORTED"),
            Self::Withdrawn => String::from("PROPOSAL_STATUS_WITHDRAWN"),
        }
    }
}

impl Default for CosmosPeriodGroupPeriodV1PeriodProposalStatus {
    fn default() -> CosmosPeriodGroupPeriodV1PeriodProposalStatus {
        Self::Unspecified
    }
}




