/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGovPeriodV1PeriodQueryVotesResponse : QueryVotesResponse is the response type for the Query/Votes RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGovPeriodV1PeriodQueryVotesResponse {
    /// votes defined the queried votes.
    #[serde(rename = "votes", skip_serializing_if = "Option::is_none")]
    pub votes: Option<Vec<crate::models::CosmosPeriodGovPeriodV1PeriodVote>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodGovPeriodV1PeriodQueryVotesResponse {
    /// QueryVotesResponse is the response type for the Query/Votes RPC method.
    pub fn new() -> CosmosPeriodGovPeriodV1PeriodQueryVotesResponse {
        CosmosPeriodGovPeriodV1PeriodQueryVotesResponse {
            votes: None,
            pagination: None,
        }
    }
}


