/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGroupPeriodV1PeriodMsgSubmitProposalResponse : MsgSubmitProposalResponse is the Msg/SubmitProposal response type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGroupPeriodV1PeriodMsgSubmitProposalResponse {
    /// proposal is the unique ID of the proposal.
    #[serde(rename = "proposalId", skip_serializing_if = "Option::is_none")]
    pub proposal_id: Option<String>,
}

impl CosmosPeriodGroupPeriodV1PeriodMsgSubmitProposalResponse {
    /// MsgSubmitProposalResponse is the Msg/SubmitProposal response type.
    pub fn new() -> CosmosPeriodGroupPeriodV1PeriodMsgSubmitProposalResponse {
        CosmosPeriodGroupPeriodV1PeriodMsgSubmitProposalResponse {
            proposal_id: None,
        }
    }
}


