/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodTxPeriodV1beta1PeriodOrderBy : - ORDER_BY_UNSPECIFIED: ORDER_BY_UNSPECIFIED specifies an unknown sorting order. OrderBy defaults to ASC in this case.  - ORDER_BY_ASC: ORDER_BY_ASC defines ascending order  - ORDER_BY_DESC: ORDER_BY_DESC defines descending order

/// - ORDER_BY_UNSPECIFIED: ORDER_BY_UNSPECIFIED specifies an unknown sorting order. OrderBy defaults to ASC in this case.  - ORDER_BY_ASC: ORDER_BY_ASC defines ascending order  - ORDER_BY_DESC: ORDER_BY_DESC defines descending order
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CosmosPeriodTxPeriodV1beta1PeriodOrderBy {
    #[serde(rename = "ORDER_BY_UNSPECIFIED")]
    Unspecified,
    #[serde(rename = "ORDER_BY_ASC")]
    Asc,
    #[serde(rename = "ORDER_BY_DESC")]
    Desc,

}

impl ToString for CosmosPeriodTxPeriodV1beta1PeriodOrderBy {
    fn to_string(&self) -> String {
        match self {
            Self::Unspecified => String::from("ORDER_BY_UNSPECIFIED"),
            Self::Asc => String::from("ORDER_BY_ASC"),
            Self::Desc => String::from("ORDER_BY_DESC"),
        }
    }
}

impl Default for CosmosPeriodTxPeriodV1beta1PeriodOrderBy {
    fn default() -> CosmosPeriodTxPeriodV1beta1PeriodOrderBy {
        Self::Unspecified
    }
}




