/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodGetBlockByHeightResponse : GetBlockByHeightResponse is the response type for the Query/GetBlockByHeight RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodGetBlockByHeightResponse {
    #[serde(rename = "blockId", skip_serializing_if = "Option::is_none")]
    pub block_id: Option<Box<crate::models::TendermintPeriodTypesPeriodBlockId>>,
    #[serde(rename = "block", skip_serializing_if = "Option::is_none")]
    pub block: Option<Box<crate::models::TendermintPeriodTypesPeriodBlock>>,
    #[serde(rename = "sdkBlock", skip_serializing_if = "Option::is_none")]
    pub sdk_block: Option<Box<crate::models::CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodBlock>>,
}

impl CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodGetBlockByHeightResponse {
    /// GetBlockByHeightResponse is the response type for the Query/GetBlockByHeight RPC method.
    pub fn new() -> CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodGetBlockByHeightResponse {
        CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodGetBlockByHeightResponse {
            block_id: None,
            block: None,
            sdk_block: None,
        }
    }
}


