/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGroupPeriodV1PeriodQueryVoteByProposalVoterResponse : QueryVoteByProposalVoterResponse is the Query/VoteByProposalVoter response type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGroupPeriodV1PeriodQueryVoteByProposalVoterResponse {
    #[serde(rename = "vote", skip_serializing_if = "Option::is_none")]
    pub vote: Option<Box<crate::models::CosmosPeriodGroupPeriodV1PeriodVote>>,
}

impl CosmosPeriodGroupPeriodV1PeriodQueryVoteByProposalVoterResponse {
    /// QueryVoteByProposalVoterResponse is the Query/VoteByProposalVoter response type.
    pub fn new() -> CosmosPeriodGroupPeriodV1PeriodQueryVoteByProposalVoterResponse {
        CosmosPeriodGroupPeriodV1PeriodQueryVoteByProposalVoterResponse {
            vote: None,
        }
    }
}


