/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGovPeriodV1PeriodWeightedVoteOption : WeightedVoteOption defines a unit of vote for vote split.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGovPeriodV1PeriodWeightedVoteOption {
    #[serde(rename = "option", skip_serializing_if = "Option::is_none")]
    pub option: Option<crate::models::CosmosPeriodGovPeriodV1PeriodVoteOption>,
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<String>,
}

impl CosmosPeriodGovPeriodV1PeriodWeightedVoteOption {
    /// WeightedVoteOption defines a unit of vote for vote split.
    pub fn new() -> CosmosPeriodGovPeriodV1PeriodWeightedVoteOption {
        CosmosPeriodGovPeriodV1PeriodWeightedVoteOption {
            option: None,
            weight: None,
        }
    }
}


