/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodParamsPeriodV1beta1PeriodQueryParamsResponse : QueryParamsResponse is response type for the Query/Params RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodParamsPeriodV1beta1PeriodQueryParamsResponse {
    #[serde(rename = "param", skip_serializing_if = "Option::is_none")]
    pub param: Option<Box<crate::models::CosmosPeriodParamsPeriodV1beta1PeriodParamChange>>,
}

impl CosmosPeriodParamsPeriodV1beta1PeriodQueryParamsResponse {
    /// QueryParamsResponse is response type for the Query/Params RPC method.
    pub fn new() -> CosmosPeriodParamsPeriodV1beta1PeriodQueryParamsResponse {
        CosmosPeriodParamsPeriodV1beta1PeriodQueryParamsResponse {
            param: None,
        }
    }
}


