/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodAuthPeriodV1beta1PeriodQueryAccountAddressByIdResponse : Since: cosmos-sdk 0.46.2



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodAuthPeriodV1beta1PeriodQueryAccountAddressByIdResponse {
    #[serde(rename = "accountAddress", skip_serializing_if = "Option::is_none")]
    pub account_address: Option<String>,
}

impl CosmosPeriodAuthPeriodV1beta1PeriodQueryAccountAddressByIdResponse {
    /// Since: cosmos-sdk 0.46.2
    pub fn new() -> CosmosPeriodAuthPeriodV1beta1PeriodQueryAccountAddressByIdResponse {
        CosmosPeriodAuthPeriodV1beta1PeriodQueryAccountAddressByIdResponse {
            account_address: None,
        }
    }
}


