/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGovPeriodV1PeriodQueryParamsResponse : QueryParamsResponse is the response type for the Query/Params RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGovPeriodV1PeriodQueryParamsResponse {
    #[serde(rename = "votingParams", skip_serializing_if = "Option::is_none")]
    pub voting_params: Option<Box<crate::models::CosmosPeriodGovPeriodV1PeriodVotingParams>>,
    #[serde(rename = "depositParams", skip_serializing_if = "Option::is_none")]
    pub deposit_params: Option<Box<crate::models::CosmosPeriodGovPeriodV1PeriodDepositParams>>,
    #[serde(rename = "tallyParams", skip_serializing_if = "Option::is_none")]
    pub tally_params: Option<Box<crate::models::CosmosPeriodGovPeriodV1PeriodTallyParams>>,
}

impl CosmosPeriodGovPeriodV1PeriodQueryParamsResponse {
    /// QueryParamsResponse is the response type for the Query/Params RPC method.
    pub fn new() -> CosmosPeriodGovPeriodV1PeriodQueryParamsResponse {
        CosmosPeriodGovPeriodV1PeriodQueryParamsResponse {
            voting_params: None,
            deposit_params: None,
            tally_params: None,
        }
    }
}


