/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGroupPeriodV1PeriodMsgCreateGroupWithPolicyResponse : MsgCreateGroupWithPolicyResponse is the Msg/CreateGroupWithPolicy response type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGroupPeriodV1PeriodMsgCreateGroupWithPolicyResponse {
    /// group_id is the unique ID of the newly created group with policy.
    #[serde(rename = "groupId", skip_serializing_if = "Option::is_none")]
    pub group_id: Option<String>,
    /// group_policy_address is the account address of the newly created group policy.
    #[serde(rename = "groupPolicyAddress", skip_serializing_if = "Option::is_none")]
    pub group_policy_address: Option<String>,
}

impl CosmosPeriodGroupPeriodV1PeriodMsgCreateGroupWithPolicyResponse {
    /// MsgCreateGroupWithPolicyResponse is the Msg/CreateGroupWithPolicy response type.
    pub fn new() -> CosmosPeriodGroupPeriodV1PeriodMsgCreateGroupWithPolicyResponse {
        CosmosPeriodGroupPeriodV1PeriodMsgCreateGroupWithPolicyResponse {
            group_id: None,
            group_policy_address: None,
        }
    }
}


