/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodAuthzPeriodV1beta1PeriodQueryGranteeGrantsResponse : QueryGranteeGrantsResponse is the response type for the Query/GranteeGrants RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodAuthzPeriodV1beta1PeriodQueryGranteeGrantsResponse {
    /// grants is a list of grants granted to the grantee.
    #[serde(rename = "grants", skip_serializing_if = "Option::is_none")]
    pub grants: Option<Vec<crate::models::CosmosPeriodAuthzPeriodV1beta1PeriodGrantAuthorization>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodAuthzPeriodV1beta1PeriodQueryGranteeGrantsResponse {
    /// QueryGranteeGrantsResponse is the response type for the Query/GranteeGrants RPC method.
    pub fn new() -> CosmosPeriodAuthzPeriodV1beta1PeriodQueryGranteeGrantsResponse {
        CosmosPeriodAuthzPeriodV1beta1PeriodQueryGranteeGrantsResponse {
            grants: None,
            pagination: None,
        }
    }
}


