/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodDistributionPeriodV1beta1PeriodQueryValidatorDistributionInfoResponse : QueryValidatorDistributionInfoResponse is the response type for the Query/ValidatorDistributionInfo RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodDistributionPeriodV1beta1PeriodQueryValidatorDistributionInfoResponse {
    /// operator_address defines the validator operator address.
    #[serde(rename = "operatorAddress", skip_serializing_if = "Option::is_none")]
    pub operator_address: Option<String>,
    /// self_bond_rewards defines the self delegations rewards.
    #[serde(rename = "selfBondRewards", skip_serializing_if = "Option::is_none")]
    pub self_bond_rewards: Option<Vec<crate::models::CosmosPeriodBasePeriodV1beta1PeriodDecCoin>>,
    /// commission defines the commision the validator received.
    #[serde(rename = "commission", skip_serializing_if = "Option::is_none")]
    pub commission: Option<Vec<crate::models::CosmosPeriodBasePeriodV1beta1PeriodDecCoin>>,
}

impl CosmosPeriodDistributionPeriodV1beta1PeriodQueryValidatorDistributionInfoResponse {
    /// QueryValidatorDistributionInfoResponse is the response type for the Query/ValidatorDistributionInfo RPC method.
    pub fn new() -> CosmosPeriodDistributionPeriodV1beta1PeriodQueryValidatorDistributionInfoResponse {
        CosmosPeriodDistributionPeriodV1beta1PeriodQueryValidatorDistributionInfoResponse {
            operator_address: None,
            self_bond_rewards: None,
            commission: None,
        }
    }
}


