/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodTxPeriodV1beta1PeriodSignerInfo : SignerInfo describes the public key and signing mode of a single top-level signer.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodTxPeriodV1beta1PeriodSignerInfo {
    #[serde(rename = "publicKey", skip_serializing_if = "Option::is_none")]
    pub public_key: Option<crate::models::GooglePeriodProtobufPeriodAny>,
    #[serde(rename = "modeInfo", skip_serializing_if = "Option::is_none")]
    pub mode_info: Option<Box<crate::models::CosmosPeriodTxPeriodV1beta1PeriodModeInfo>>,
    /// sequence is the sequence of the account, which describes the number of committed transactions signed by a given address. It is used to prevent replay attacks.
    #[serde(rename = "sequence", skip_serializing_if = "Option::is_none")]
    pub sequence: Option<String>,
}

impl CosmosPeriodTxPeriodV1beta1PeriodSignerInfo {
    /// SignerInfo describes the public key and signing mode of a single top-level signer.
    pub fn new() -> CosmosPeriodTxPeriodV1beta1PeriodSignerInfo {
        CosmosPeriodTxPeriodV1beta1PeriodSignerInfo {
            public_key: None,
            mode_info: None,
            sequence: None,
        }
    }
}


