/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGroupPeriodV1PeriodMsgCreateGroupPolicyResponse : MsgCreateGroupPolicyResponse is the Msg/CreateGroupPolicy response type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGroupPeriodV1PeriodMsgCreateGroupPolicyResponse {
    /// address is the account address of the newly created group policy.
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
}

impl CosmosPeriodGroupPeriodV1PeriodMsgCreateGroupPolicyResponse {
    /// MsgCreateGroupPolicyResponse is the Msg/CreateGroupPolicy response type.
    pub fn new() -> CosmosPeriodGroupPeriodV1PeriodMsgCreateGroupPolicyResponse {
        CosmosPeriodGroupPeriodV1PeriodMsgCreateGroupPolicyResponse {
            address: None,
        }
    }
}


