/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodAuthPeriodV1beta1PeriodAddressBytesToStringResponse : AddressBytesToStringResponse is the response type for AddressString rpc method.  Since: cosmos-sdk 0.46



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodAuthPeriodV1beta1PeriodAddressBytesToStringResponse {
    #[serde(rename = "addressString", skip_serializing_if = "Option::is_none")]
    pub address_string: Option<String>,
}

impl CosmosPeriodAuthPeriodV1beta1PeriodAddressBytesToStringResponse {
    /// AddressBytesToStringResponse is the response type for AddressString rpc method.  Since: cosmos-sdk 0.46
    pub fn new() -> CosmosPeriodAuthPeriodV1beta1PeriodAddressBytesToStringResponse {
        CosmosPeriodAuthPeriodV1beta1PeriodAddressBytesToStringResponse {
            address_string: None,
        }
    }
}


