/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodNftPeriodV1beta1PeriodQueryClassResponse {
    #[serde(rename = "class", skip_serializing_if = "Option::is_none")]
    pub class: Option<Box<crate::models::CosmosPeriodNftPeriodV1beta1PeriodClass>>,
}

impl CosmosPeriodNftPeriodV1beta1PeriodQueryClassResponse {
    pub fn new() -> CosmosPeriodNftPeriodV1beta1PeriodQueryClassResponse {
        CosmosPeriodNftPeriodV1beta1PeriodQueryClassResponse {
            class: None,
        }
    }
}


