/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodStakingPeriodV1beta1PeriodQueryUnbondingDelegationResponse : QueryDelegationResponse is response type for the Query/UnbondingDelegation RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodStakingPeriodV1beta1PeriodQueryUnbondingDelegationResponse {
    #[serde(rename = "unbond", skip_serializing_if = "Option::is_none")]
    pub unbond: Option<Box<crate::models::CosmosPeriodStakingPeriodV1beta1PeriodUnbondingDelegation>>,
}

impl CosmosPeriodStakingPeriodV1beta1PeriodQueryUnbondingDelegationResponse {
    /// QueryDelegationResponse is response type for the Query/UnbondingDelegation RPC method.
    pub fn new() -> CosmosPeriodStakingPeriodV1beta1PeriodQueryUnbondingDelegationResponse {
        CosmosPeriodStakingPeriodV1beta1PeriodQueryUnbondingDelegationResponse {
            unbond: None,
        }
    }
}


