/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodDistributionPeriodV1beta1PeriodValidatorSlashEvent : ValidatorSlashEvent represents a validator slash event. Height is implicit within the store key. This is needed to calculate appropriate amount of staking tokens for delegations which are withdrawn after a slash has occurred.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodDistributionPeriodV1beta1PeriodValidatorSlashEvent {
    #[serde(rename = "validatorPeriod", skip_serializing_if = "Option::is_none")]
    pub validator_period: Option<String>,
    #[serde(rename = "fraction", skip_serializing_if = "Option::is_none")]
    pub fraction: Option<String>,
}

impl CosmosPeriodDistributionPeriodV1beta1PeriodValidatorSlashEvent {
    /// ValidatorSlashEvent represents a validator slash event. Height is implicit within the store key. This is needed to calculate appropriate amount of staking tokens for delegations which are withdrawn after a slash has occurred.
    pub fn new() -> CosmosPeriodDistributionPeriodV1beta1PeriodValidatorSlashEvent {
        CosmosPeriodDistributionPeriodV1beta1PeriodValidatorSlashEvent {
            validator_period: None,
            fraction: None,
        }
    }
}


