/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodTxPeriodV1beta1PeriodGetTxsEventResponse : GetTxsEventResponse is the response type for the Service.TxsByEvents RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodTxPeriodV1beta1PeriodGetTxsEventResponse {
    /// txs is the list of queried transactions.
    #[serde(rename = "txs", skip_serializing_if = "Option::is_none")]
    pub txs: Option<Vec<crate::models::CosmosPeriodTxPeriodV1beta1PeriodTx>>,
    /// tx_responses is the list of queried TxResponses.
    #[serde(rename = "txResponses", skip_serializing_if = "Option::is_none")]
    pub tx_responses: Option<Vec<crate::models::CosmosPeriodBasePeriodAbciPeriodV1beta1PeriodTxResponse>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<String>,
}

impl CosmosPeriodTxPeriodV1beta1PeriodGetTxsEventResponse {
    /// GetTxsEventResponse is the response type for the Service.TxsByEvents RPC method.
    pub fn new() -> CosmosPeriodTxPeriodV1beta1PeriodGetTxsEventResponse {
        CosmosPeriodTxPeriodV1beta1PeriodGetTxsEventResponse {
            txs: None,
            tx_responses: None,
            pagination: None,
            total: None,
        }
    }
}


