/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodMintPeriodV1beta1PeriodQueryAnnualProvisionsResponse : QueryAnnualProvisionsResponse is the response type for the Query/AnnualProvisions RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodMintPeriodV1beta1PeriodQueryAnnualProvisionsResponse {
    /// annual_provisions is the current minting annual provisions value.
    #[serde(rename = "annualProvisions", skip_serializing_if = "Option::is_none")]
    pub annual_provisions: Option<String>,
}

impl CosmosPeriodMintPeriodV1beta1PeriodQueryAnnualProvisionsResponse {
    /// QueryAnnualProvisionsResponse is the response type for the Query/AnnualProvisions RPC method.
    pub fn new() -> CosmosPeriodMintPeriodV1beta1PeriodQueryAnnualProvisionsResponse {
        CosmosPeriodMintPeriodV1beta1PeriodQueryAnnualProvisionsResponse {
            annual_provisions: None,
        }
    }
}


