/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodStakingPeriodV1beta1PeriodQueryDelegatorValidatorResponse : QueryDelegatorValidatorResponse response type for the Query/DelegatorValidator RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodStakingPeriodV1beta1PeriodQueryDelegatorValidatorResponse {
    #[serde(rename = "validator", skip_serializing_if = "Option::is_none")]
    pub validator: Option<Box<crate::models::CosmosPeriodStakingPeriodV1beta1PeriodValidator>>,
}

impl CosmosPeriodStakingPeriodV1beta1PeriodQueryDelegatorValidatorResponse {
    /// QueryDelegatorValidatorResponse response type for the Query/DelegatorValidator RPC method.
    pub fn new() -> CosmosPeriodStakingPeriodV1beta1PeriodQueryDelegatorValidatorResponse {
        CosmosPeriodStakingPeriodV1beta1PeriodQueryDelegatorValidatorResponse {
            validator: None,
        }
    }
}


