/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodBasePeriodAbciPeriodV1beta1PeriodAttribute : Attribute defines an attribute wrapper where the key and value are strings instead of raw bytes.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodAbciPeriodV1beta1PeriodAttribute {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl CosmosPeriodBasePeriodAbciPeriodV1beta1PeriodAttribute {
    /// Attribute defines an attribute wrapper where the key and value are strings instead of raw bytes.
    pub fn new() -> CosmosPeriodBasePeriodAbciPeriodV1beta1PeriodAttribute {
        CosmosPeriodBasePeriodAbciPeriodV1beta1PeriodAttribute {
            key: None,
            value: None,
        }
    }
}


