/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodSlashingPeriodV1beta1PeriodQueryParamsResponse {
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Box<crate::models::CosmosPeriodSlashingPeriodV1beta1PeriodParams>>,
}

impl CosmosPeriodSlashingPeriodV1beta1PeriodQueryParamsResponse {
    pub fn new() -> CosmosPeriodSlashingPeriodV1beta1PeriodQueryParamsResponse {
        CosmosPeriodSlashingPeriodV1beta1PeriodQueryParamsResponse {
            params: None,
        }
    }
}


