/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodHeader : Header defines the structure of a Tendermint block header.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodHeader {
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<Box<crate::models::TendermintPeriodVersionPeriodConsensus>>,
    #[serde(rename = "chainId", skip_serializing_if = "Option::is_none")]
    pub chain_id: Option<String>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
    #[serde(rename = "lastBlockId", skip_serializing_if = "Option::is_none")]
    pub last_block_id: Option<Box<crate::models::TendermintPeriodTypesPeriodBlockId>>,
    /// commit from validators from the last block
    #[serde(rename = "lastCommitHash", skip_serializing_if = "Option::is_none")]
    pub last_commit_hash: Option<String>,
    #[serde(rename = "dataHash", skip_serializing_if = "Option::is_none")]
    pub data_hash: Option<String>,
    /// validators for the current block
    #[serde(rename = "validatorsHash", skip_serializing_if = "Option::is_none")]
    pub validators_hash: Option<String>,
    #[serde(rename = "nextValidatorsHash", skip_serializing_if = "Option::is_none")]
    pub next_validators_hash: Option<String>,
    #[serde(rename = "consensusHash", skip_serializing_if = "Option::is_none")]
    pub consensus_hash: Option<String>,
    #[serde(rename = "appHash", skip_serializing_if = "Option::is_none")]
    pub app_hash: Option<String>,
    #[serde(rename = "lastResultsHash", skip_serializing_if = "Option::is_none")]
    pub last_results_hash: Option<String>,
    /// evidence included in the block
    #[serde(rename = "evidenceHash", skip_serializing_if = "Option::is_none")]
    pub evidence_hash: Option<String>,
    /// proposer_address is the original block proposer address, formatted as a Bech32 string. In Tendermint, this type is `bytes`, but in the SDK, we convert it to a Bech32 string for better UX.  original proposer of the block
    #[serde(rename = "proposerAddress", skip_serializing_if = "Option::is_none")]
    pub proposer_address: Option<String>,
}

impl CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodHeader {
    /// Header defines the structure of a Tendermint block header.
    pub fn new() -> CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodHeader {
        CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodHeader {
            version: None,
            chain_id: None,
            height: None,
            time: None,
            last_block_id: None,
            last_commit_hash: None,
            data_hash: None,
            validators_hash: None,
            next_validators_hash: None,
            consensus_hash: None,
            app_hash: None,
            last_results_hash: None,
            evidence_hash: None,
            proposer_address: None,
        }
    }
}


