/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodInterfaceAcceptingMessageDescriptor {
    #[serde(rename = "fullname", skip_serializing_if = "Option::is_none")]
    pub fullname: Option<String>,
    #[serde(rename = "fieldDescriptorNames", skip_serializing_if = "Option::is_none")]
    pub field_descriptor_names: Option<Vec<String>>,
}

impl CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodInterfaceAcceptingMessageDescriptor {
    pub fn new() -> CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodInterfaceAcceptingMessageDescriptor {
        CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodInterfaceAcceptingMessageDescriptor {
            fullname: None,
            field_descriptor_names: None,
        }
    }
}


