/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGovPeriodV1beta1PeriodDepositParams : DepositParams defines the params for deposits on governance proposals.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGovPeriodV1beta1PeriodDepositParams {
    /// Minimum deposit for a proposal to enter voting period.
    #[serde(rename = "minDeposit", skip_serializing_if = "Option::is_none")]
    pub min_deposit: Option<Vec<crate::models::CosmosPeriodBasePeriodV1beta1PeriodCoin>>,
    /// Maximum period for Atom holders to deposit on a proposal. Initial value: 2  months.
    #[serde(rename = "maxDepositPeriod", skip_serializing_if = "Option::is_none")]
    pub max_deposit_period: Option<String>,
}

impl CosmosPeriodGovPeriodV1beta1PeriodDepositParams {
    /// DepositParams defines the params for deposits on governance proposals.
    pub fn new() -> CosmosPeriodGovPeriodV1beta1PeriodDepositParams {
        CosmosPeriodGovPeriodV1beta1PeriodDepositParams {
            min_deposit: None,
            max_deposit_period: None,
        }
    }
}


