/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodTxPeriodV1beta1PeriodBroadcastTxRequest : BroadcastTxRequest is the request type for the Service.BroadcastTxRequest RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodTxPeriodV1beta1PeriodBroadcastTxRequest {
    /// tx_bytes is the raw transaction.
    #[serde(rename = "txBytes", skip_serializing_if = "Option::is_none")]
    pub tx_bytes: Option<String>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<crate::models::CosmosPeriodTxPeriodV1beta1PeriodBroadcastMode>,
}

impl CosmosPeriodTxPeriodV1beta1PeriodBroadcastTxRequest {
    /// BroadcastTxRequest is the request type for the Service.BroadcastTxRequest RPC method.
    pub fn new() -> CosmosPeriodTxPeriodV1beta1PeriodBroadcastTxRequest {
        CosmosPeriodTxPeriodV1beta1PeriodBroadcastTxRequest {
            tx_bytes: None,
            mode: None,
        }
    }
}


