/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGroupPeriodV1PeriodQueryGroupsByAdminResponse : QueryGroupsByAdminResponse is the Query/GroupsByAdminResponse response type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGroupPeriodV1PeriodQueryGroupsByAdminResponse {
    /// groups are the groups info with the provided admin.
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Vec<crate::models::CosmosPeriodGroupPeriodV1PeriodGroupInfo>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodGroupPeriodV1PeriodQueryGroupsByAdminResponse {
    /// QueryGroupsByAdminResponse is the Query/GroupsByAdminResponse response type.
    pub fn new() -> CosmosPeriodGroupPeriodV1PeriodQueryGroupsByAdminResponse {
        CosmosPeriodGroupPeriodV1PeriodQueryGroupsByAdminResponse {
            groups: None,
            pagination: None,
        }
    }
}


