/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGroupPeriodV1PeriodGroupInfo : GroupInfo represents the high-level on-chain information for a group.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGroupPeriodV1PeriodGroupInfo {
    /// id is the unique ID of the group.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// admin is the account address of the group's admin.
    #[serde(rename = "admin", skip_serializing_if = "Option::is_none")]
    pub admin: Option<String>,
    /// metadata is any arbitrary metadata to attached to the group.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// total_weight is the sum of the group members' weights.
    #[serde(rename = "totalWeight", skip_serializing_if = "Option::is_none")]
    pub total_weight: Option<String>,
    /// created_at is a timestamp specifying when a group was created.
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
}

impl CosmosPeriodGroupPeriodV1PeriodGroupInfo {
    /// GroupInfo represents the high-level on-chain information for a group.
    pub fn new() -> CosmosPeriodGroupPeriodV1PeriodGroupInfo {
        CosmosPeriodGroupPeriodV1PeriodGroupInfo {
            id: None,
            admin: None,
            metadata: None,
            version: None,
            total_weight: None,
            created_at: None,
        }
    }
}


