/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodAuthPeriodV1beta1PeriodQueryModuleAccountsResponse : QueryModuleAccountsResponse is the response type for the Query/ModuleAccounts RPC method.  Since: cosmos-sdk 0.46



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodAuthPeriodV1beta1PeriodQueryModuleAccountsResponse {
    #[serde(rename = "accounts", skip_serializing_if = "Option::is_none")]
    pub accounts: Option<Vec<crate::models::GooglePeriodProtobufPeriodAny>>,
}

impl CosmosPeriodAuthPeriodV1beta1PeriodQueryModuleAccountsResponse {
    /// QueryModuleAccountsResponse is the response type for the Query/ModuleAccounts RPC method.  Since: cosmos-sdk 0.46
    pub fn new() -> CosmosPeriodAuthPeriodV1beta1PeriodQueryModuleAccountsResponse {
        CosmosPeriodAuthPeriodV1beta1PeriodQueryModuleAccountsResponse {
            accounts: None,
        }
    }
}


