/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodDistributionPeriodV1beta1PeriodValidatorAccumulatedCommission : ValidatorAccumulatedCommission represents accumulated commission for a validator kept as a running counter, can be withdrawn at any time.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodDistributionPeriodV1beta1PeriodValidatorAccumulatedCommission {
    #[serde(rename = "commission", skip_serializing_if = "Option::is_none")]
    pub commission: Option<Vec<crate::models::CosmosPeriodBasePeriodV1beta1PeriodDecCoin>>,
}

impl CosmosPeriodDistributionPeriodV1beta1PeriodValidatorAccumulatedCommission {
    /// ValidatorAccumulatedCommission represents accumulated commission for a validator kept as a running counter, can be withdrawn at any time.
    pub fn new() -> CosmosPeriodDistributionPeriodV1beta1PeriodValidatorAccumulatedCommission {
        CosmosPeriodDistributionPeriodV1beta1PeriodValidatorAccumulatedCommission {
            commission: None,
        }
    }
}


