/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodAuthPeriodV1beta1PeriodParams : Params defines the parameters for the auth module.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodAuthPeriodV1beta1PeriodParams {
    #[serde(rename = "maxMemoCharacters", skip_serializing_if = "Option::is_none")]
    pub max_memo_characters: Option<String>,
    #[serde(rename = "txSigLimit", skip_serializing_if = "Option::is_none")]
    pub tx_sig_limit: Option<String>,
    #[serde(rename = "txSizeCostPerByte", skip_serializing_if = "Option::is_none")]
    pub tx_size_cost_per_byte: Option<String>,
    #[serde(rename = "sigVerifyCostEd25519", skip_serializing_if = "Option::is_none")]
    pub sig_verify_cost_ed25519: Option<String>,
    #[serde(rename = "sigVerifyCostSecp256k1", skip_serializing_if = "Option::is_none")]
    pub sig_verify_cost_secp256k1: Option<String>,
}

impl CosmosPeriodAuthPeriodV1beta1PeriodParams {
    /// Params defines the parameters for the auth module.
    pub fn new() -> CosmosPeriodAuthPeriodV1beta1PeriodParams {
        CosmosPeriodAuthPeriodV1beta1PeriodParams {
            max_memo_characters: None,
            tx_sig_limit: None,
            tx_size_cost_per_byte: None,
            sig_verify_cost_ed25519: None,
            sig_verify_cost_secp256k1: None,
        }
    }
}


