/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodBankPeriodV1beta1PeriodParams : Params defines the parameters for the bank module.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBankPeriodV1beta1PeriodParams {
    #[serde(rename = "sendEnabled", skip_serializing_if = "Option::is_none")]
    pub send_enabled: Option<Vec<crate::models::CosmosPeriodBankPeriodV1beta1PeriodSendEnabled>>,
    #[serde(rename = "defaultSendEnabled", skip_serializing_if = "Option::is_none")]
    pub default_send_enabled: Option<bool>,
}

impl CosmosPeriodBankPeriodV1beta1PeriodParams {
    /// Params defines the parameters for the bank module.
    pub fn new() -> CosmosPeriodBankPeriodV1beta1PeriodParams {
        CosmosPeriodBankPeriodV1beta1PeriodParams {
            send_enabled: None,
            default_send_enabled: None,
        }
    }
}


