/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodModule {
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "sum", skip_serializing_if = "Option::is_none")]
    pub sum: Option<String>,
}

impl CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodModule {
    pub fn new() -> CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodModule {
        CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodModule {
            path: None,
            version: None,
            sum: None,
        }
    }
}


