/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodAppPeriodV1alpha1PeriodModuleConfig : ModuleConfig is a module configuration for an app.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodAppPeriodV1alpha1PeriodModuleConfig {
    /// name is the unique name of the module within the app. It should be a name that persists between different versions of a module so that modules can be smoothly upgraded to new versions.  For example, for the module cosmos.bank.module.v1.Module, we may chose to simply name the module \"bank\" in the app. When we upgrade to cosmos.bank.module.v2.Module, the app-specific name \"bank\" stays the same and the framework knows that the v2 module should receive all the same state that the v1 module had. Note: modules should provide info on which versions they can migrate from in the ModuleDescriptor.can_migration_from field.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<crate::models::GooglePeriodProtobufPeriodAny>,
}

impl CosmosPeriodAppPeriodV1alpha1PeriodModuleConfig {
    /// ModuleConfig is a module configuration for an app.
    pub fn new() -> CosmosPeriodAppPeriodV1alpha1PeriodModuleConfig {
        CosmosPeriodAppPeriodV1alpha1PeriodModuleConfig {
            name: None,
            config: None,
        }
    }
}


