/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodBasePeriodNodePeriodV1beta1PeriodConfigResponse : ConfigResponse defines the response structure for the Config gRPC query.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodNodePeriodV1beta1PeriodConfigResponse {
    #[serde(rename = "minimumGasPrice", skip_serializing_if = "Option::is_none")]
    pub minimum_gas_price: Option<String>,
}

impl CosmosPeriodBasePeriodNodePeriodV1beta1PeriodConfigResponse {
    /// ConfigResponse defines the response structure for the Config gRPC query.
    pub fn new() -> CosmosPeriodBasePeriodNodePeriodV1beta1PeriodConfigResponse {
        CosmosPeriodBasePeriodNodePeriodV1beta1PeriodConfigResponse {
            minimum_gas_price: None,
        }
    }
}


