/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodStakingPeriodV1beta1PeriodQueryValidatorUnbondingDelegationsResponse : QueryValidatorUnbondingDelegationsResponse is response type for the Query/ValidatorUnbondingDelegations RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodStakingPeriodV1beta1PeriodQueryValidatorUnbondingDelegationsResponse {
    #[serde(rename = "unbondingResponses", skip_serializing_if = "Option::is_none")]
    pub unbonding_responses: Option<Vec<crate::models::CosmosPeriodStakingPeriodV1beta1PeriodUnbondingDelegation>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodStakingPeriodV1beta1PeriodQueryValidatorUnbondingDelegationsResponse {
    /// QueryValidatorUnbondingDelegationsResponse is response type for the Query/ValidatorUnbondingDelegations RPC method.
    pub fn new() -> CosmosPeriodStakingPeriodV1beta1PeriodQueryValidatorUnbondingDelegationsResponse {
        CosmosPeriodStakingPeriodV1beta1PeriodQueryValidatorUnbondingDelegationsResponse {
            unbonding_responses: None,
            pagination: None,
        }
    }
}


