/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodAuthPeriodV1beta1PeriodQueryAccountsResponse : QueryAccountsResponse is the response type for the Query/Accounts RPC method.  Since: cosmos-sdk 0.43



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodAuthPeriodV1beta1PeriodQueryAccountsResponse {
    #[serde(rename = "accounts", skip_serializing_if = "Option::is_none")]
    pub accounts: Option<Vec<crate::models::GooglePeriodProtobufPeriodAny>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodAuthPeriodV1beta1PeriodQueryAccountsResponse {
    /// QueryAccountsResponse is the response type for the Query/Accounts RPC method.  Since: cosmos-sdk 0.43
    pub fn new() -> CosmosPeriodAuthPeriodV1beta1PeriodQueryAccountsResponse {
        CosmosPeriodAuthPeriodV1beta1PeriodQueryAccountsResponse {
            accounts: None,
            pagination: None,
        }
    }
}


