/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGroupPeriodV1PeriodGroupMember : GroupMember represents the relationship between a group and a member.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGroupPeriodV1PeriodGroupMember {
    /// group_id is the unique ID of the group.
    #[serde(rename = "groupId", skip_serializing_if = "Option::is_none")]
    pub group_id: Option<String>,
    #[serde(rename = "member", skip_serializing_if = "Option::is_none")]
    pub member: Option<Box<crate::models::CosmosPeriodGroupPeriodV1PeriodMember>>,
}

impl CosmosPeriodGroupPeriodV1PeriodGroupMember {
    /// GroupMember represents the relationship between a group and a member.
    pub fn new() -> CosmosPeriodGroupPeriodV1PeriodGroupMember {
        CosmosPeriodGroupPeriodV1PeriodGroupMember {
            group_id: None,
            member: None,
        }
    }
}


