/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGovPeriodV1PeriodTallyParams : TallyParams defines the params for tallying votes on governance proposals.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGovPeriodV1PeriodTallyParams {
    /// Minimum percentage of total stake needed to vote for a result to be  considered valid.
    #[serde(rename = "quorum", skip_serializing_if = "Option::is_none")]
    pub quorum: Option<String>,
    /// Minimum proportion of Yes votes for proposal to pass. Default value: 0.5.
    #[serde(rename = "threshold", skip_serializing_if = "Option::is_none")]
    pub threshold: Option<String>,
    /// Minimum value of Veto votes to Total votes ratio for proposal to be  vetoed. Default value: 1/3.
    #[serde(rename = "vetoThreshold", skip_serializing_if = "Option::is_none")]
    pub veto_threshold: Option<String>,
}

impl CosmosPeriodGovPeriodV1PeriodTallyParams {
    /// TallyParams defines the params for tallying votes on governance proposals.
    pub fn new() -> CosmosPeriodGovPeriodV1PeriodTallyParams {
        CosmosPeriodGovPeriodV1PeriodTallyParams {
            quorum: None,
            threshold: None,
            veto_threshold: None,
        }
    }
}


