/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodStakingPeriodV1beta1PeriodRedelegation : Redelegation contains the list of a particular delegator's redelegating bonds from a particular source validator to a particular destination validator.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodStakingPeriodV1beta1PeriodRedelegation {
    /// delegator_address is the bech32-encoded address of the delegator.
    #[serde(rename = "delegatorAddress", skip_serializing_if = "Option::is_none")]
    pub delegator_address: Option<String>,
    /// validator_src_address is the validator redelegation source operator address.
    #[serde(rename = "validatorSrcAddress", skip_serializing_if = "Option::is_none")]
    pub validator_src_address: Option<String>,
    /// validator_dst_address is the validator redelegation destination operator address.
    #[serde(rename = "validatorDstAddress", skip_serializing_if = "Option::is_none")]
    pub validator_dst_address: Option<String>,
    /// entries are the redelegation entries.  redelegation entries
    #[serde(rename = "entries", skip_serializing_if = "Option::is_none")]
    pub entries: Option<Vec<crate::models::CosmosPeriodStakingPeriodV1beta1PeriodRedelegationEntry>>,
}

impl CosmosPeriodStakingPeriodV1beta1PeriodRedelegation {
    /// Redelegation contains the list of a particular delegator's redelegating bonds from a particular source validator to a particular destination validator.
    pub fn new() -> CosmosPeriodStakingPeriodV1beta1PeriodRedelegation {
        CosmosPeriodStakingPeriodV1beta1PeriodRedelegation {
            delegator_address: None,
            validator_src_address: None,
            validator_dst_address: None,
            entries: None,
        }
    }
}


