/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodStakingPeriodV1beta1PeriodHistoricalInfo : HistoricalInfo contains header and validator information for a given block. It is stored as part of staking module's state, which persists the `n` most recent HistoricalInfo (`n` is set by the staking module's `historical_entries` parameter).



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodStakingPeriodV1beta1PeriodHistoricalInfo {
    #[serde(rename = "header", skip_serializing_if = "Option::is_none")]
    pub header: Option<Box<crate::models::TendermintPeriodTypesPeriodHeader>>,
    #[serde(rename = "valset", skip_serializing_if = "Option::is_none")]
    pub valset: Option<Vec<crate::models::CosmosPeriodStakingPeriodV1beta1PeriodValidator>>,
}

impl CosmosPeriodStakingPeriodV1beta1PeriodHistoricalInfo {
    /// HistoricalInfo contains header and validator information for a given block. It is stored as part of staking module's state, which persists the `n` most recent HistoricalInfo (`n` is set by the staking module's `historical_entries` parameter).
    pub fn new() -> CosmosPeriodStakingPeriodV1beta1PeriodHistoricalInfo {
        CosmosPeriodStakingPeriodV1beta1PeriodHistoricalInfo {
            header: None,
            valset: None,
        }
    }
}


