/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodQueryServicesDescriptor {
    #[serde(rename = "queryServices", skip_serializing_if = "Option::is_none")]
    pub query_services: Option<Vec<crate::models::CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodQueryServiceDescriptor>>,
}

impl CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodQueryServicesDescriptor {
    pub fn new() -> CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodQueryServicesDescriptor {
        CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodQueryServicesDescriptor {
            query_services: None,
        }
    }
}


