/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodUpgradePeriodV1beta1PeriodQueryUpgradedConsensusStateResponse : QueryUpgradedConsensusStateResponse is the response type for the Query/UpgradedConsensusState RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodUpgradePeriodV1beta1PeriodQueryUpgradedConsensusStateResponse {
    #[serde(rename = "upgradedConsensusState", skip_serializing_if = "Option::is_none")]
    pub upgraded_consensus_state: Option<String>,
}

impl CosmosPeriodUpgradePeriodV1beta1PeriodQueryUpgradedConsensusStateResponse {
    /// QueryUpgradedConsensusStateResponse is the response type for the Query/UpgradedConsensusState RPC method.
    pub fn new() -> CosmosPeriodUpgradePeriodV1beta1PeriodQueryUpgradedConsensusStateResponse {
        CosmosPeriodUpgradePeriodV1beta1PeriodQueryUpgradedConsensusStateResponse {
            upgraded_consensus_state: None,
        }
    }
}


