/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodSigningModeDescriptor {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "number", skip_serializing_if = "Option::is_none")]
    pub number: Option<i32>,
    #[serde(rename = "authnInfoProviderMethodFullname", skip_serializing_if = "Option::is_none")]
    pub authn_info_provider_method_fullname: Option<String>,
}

impl CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodSigningModeDescriptor {
    pub fn new() -> CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodSigningModeDescriptor {
        CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodSigningModeDescriptor {
            name: None,
            number: None,
            authn_info_provider_method_fullname: None,
        }
    }
}


