/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodVersionInfo : VersionInfo is the type for the GetNodeInfoResponse message.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodVersionInfo {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "appName", skip_serializing_if = "Option::is_none")]
    pub app_name: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "gitCommit", skip_serializing_if = "Option::is_none")]
    pub git_commit: Option<String>,
    #[serde(rename = "buildTags", skip_serializing_if = "Option::is_none")]
    pub build_tags: Option<String>,
    #[serde(rename = "goVersion", skip_serializing_if = "Option::is_none")]
    pub go_version: Option<String>,
    #[serde(rename = "buildDeps", skip_serializing_if = "Option::is_none")]
    pub build_deps: Option<Vec<crate::models::CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodModule>>,
    #[serde(rename = "cosmosSdkVersion", skip_serializing_if = "Option::is_none")]
    pub cosmos_sdk_version: Option<String>,
}

impl CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodVersionInfo {
    /// VersionInfo is the type for the GetNodeInfoResponse message.
    pub fn new() -> CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodVersionInfo {
        CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodVersionInfo {
            name: None,
            app_name: None,
            version: None,
            git_commit: None,
            build_tags: None,
            go_version: None,
            build_deps: None,
            cosmos_sdk_version: None,
        }
    }
}


