/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodTxDescriptor {
    /// fullname is the protobuf fullname of the raw transaction type (for instance the tx.Tx type) it is not meant to support polymorphism of transaction types, it is supposed to be used by reflection clients to understand if they can handle a specific transaction type in an application.
    #[serde(rename = "fullname", skip_serializing_if = "Option::is_none")]
    pub fullname: Option<String>,
    #[serde(rename = "msgs", skip_serializing_if = "Option::is_none")]
    pub msgs: Option<Vec<crate::models::CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodMsgDescriptor>>,
}

impl CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodTxDescriptor {
    pub fn new() -> CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodTxDescriptor {
        CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodTxDescriptor {
            fullname: None,
            msgs: None,
        }
    }
}


