/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodStakingPeriodV1beta1PeriodRedelegationEntryResponse : RedelegationEntryResponse is equivalent to a RedelegationEntry except that it contains a balance in addition to shares which is more suitable for client responses.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodStakingPeriodV1beta1PeriodRedelegationEntryResponse {
    #[serde(rename = "redelegationEntry", skip_serializing_if = "Option::is_none")]
    pub redelegation_entry: Option<Box<crate::models::CosmosPeriodStakingPeriodV1beta1PeriodRedelegationEntry>>,
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<String>,
}

impl CosmosPeriodStakingPeriodV1beta1PeriodRedelegationEntryResponse {
    /// RedelegationEntryResponse is equivalent to a RedelegationEntry except that it contains a balance in addition to shares which is more suitable for client responses.
    pub fn new() -> CosmosPeriodStakingPeriodV1beta1PeriodRedelegationEntryResponse {
        CosmosPeriodStakingPeriodV1beta1PeriodRedelegationEntryResponse {
            redelegation_entry: None,
            balance: None,
        }
    }
}


