/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodAuthnDescriptor {
    #[serde(rename = "signModes", skip_serializing_if = "Option::is_none")]
    pub sign_modes: Option<Vec<crate::models::CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodSigningModeDescriptor>>,
}

impl CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodAuthnDescriptor {
    pub fn new() -> CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodAuthnDescriptor {
        CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodAuthnDescriptor {
            sign_modes: None,
        }
    }
}


