/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodEvidencePeriodV1beta1PeriodQueryEvidenceResponse : QueryEvidenceResponse is the response type for the Query/Evidence RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodEvidencePeriodV1beta1PeriodQueryEvidenceResponse {
    #[serde(rename = "evidence", skip_serializing_if = "Option::is_none")]
    pub evidence: Option<crate::models::GooglePeriodProtobufPeriodAny>,
}

impl CosmosPeriodEvidencePeriodV1beta1PeriodQueryEvidenceResponse {
    /// QueryEvidenceResponse is the response type for the Query/Evidence RPC method.
    pub fn new() -> CosmosPeriodEvidencePeriodV1beta1PeriodQueryEvidenceResponse {
        CosmosPeriodEvidencePeriodV1beta1PeriodQueryEvidenceResponse {
            evidence: None,
        }
    }
}


