/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodStakingPeriodV1beta1PeriodUnbondingDelegationEntry : UnbondingDelegationEntry defines an unbonding object with relevant metadata.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodStakingPeriodV1beta1PeriodUnbondingDelegationEntry {
    /// creation_height is the height which the unbonding took place.
    #[serde(rename = "creationHeight", skip_serializing_if = "Option::is_none")]
    pub creation_height: Option<String>,
    /// completion_time is the unix time for unbonding completion.
    #[serde(rename = "completionTime", skip_serializing_if = "Option::is_none")]
    pub completion_time: Option<String>,
    /// initial_balance defines the tokens initially scheduled to receive at completion.
    #[serde(rename = "initialBalance", skip_serializing_if = "Option::is_none")]
    pub initial_balance: Option<String>,
    /// balance defines the tokens to receive at completion.
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<String>,
}

impl CosmosPeriodStakingPeriodV1beta1PeriodUnbondingDelegationEntry {
    /// UnbondingDelegationEntry defines an unbonding object with relevant metadata.
    pub fn new() -> CosmosPeriodStakingPeriodV1beta1PeriodUnbondingDelegationEntry {
        CosmosPeriodStakingPeriodV1beta1PeriodUnbondingDelegationEntry {
            creation_height: None,
            completion_time: None,
            initial_balance: None,
            balance: None,
        }
    }
}


