/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodGetAuthnDescriptorResponse {
    #[serde(rename = "authn", skip_serializing_if = "Option::is_none")]
    pub authn: Option<Box<crate::models::CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodAuthnDescriptor>>,
}

impl CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodGetAuthnDescriptorResponse {
    pub fn new() -> CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodGetAuthnDescriptorResponse {
        CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodGetAuthnDescriptorResponse {
            authn: None,
        }
    }
}


