/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodParamsPeriodV1beta1PeriodParamChange : ParamChange defines an individual parameter change, for use in ParameterChangeProposal.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodParamsPeriodV1beta1PeriodParamChange {
    #[serde(rename = "subspace", skip_serializing_if = "Option::is_none")]
    pub subspace: Option<String>,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl CosmosPeriodParamsPeriodV1beta1PeriodParamChange {
    /// ParamChange defines an individual parameter change, for use in ParameterChangeProposal.
    pub fn new() -> CosmosPeriodParamsPeriodV1beta1PeriodParamChange {
        CosmosPeriodParamsPeriodV1beta1PeriodParamChange {
            subspace: None,
            key: None,
            value: None,
        }
    }
}


