/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodAuthzPeriodV1beta1PeriodGrantAuthorization {
    #[serde(rename = "granter", skip_serializing_if = "Option::is_none")]
    pub granter: Option<String>,
    #[serde(rename = "grantee", skip_serializing_if = "Option::is_none")]
    pub grantee: Option<String>,
    #[serde(rename = "authorization", skip_serializing_if = "Option::is_none")]
    pub authorization: Option<crate::models::GooglePeriodProtobufPeriodAny>,
    #[serde(rename = "expiration", skip_serializing_if = "Option::is_none")]
    pub expiration: Option<String>,
}

impl CosmosPeriodAuthzPeriodV1beta1PeriodGrantAuthorization {
    pub fn new() -> CosmosPeriodAuthzPeriodV1beta1PeriodGrantAuthorization {
        CosmosPeriodAuthzPeriodV1beta1PeriodGrantAuthorization {
            granter: None,
            grantee: None,
            authorization: None,
            expiration: None,
        }
    }
}


