/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodBankPeriodV1beta1PeriodQueryDenomsMetadataResponse : QueryDenomsMetadataResponse is the response type for the Query/DenomsMetadata RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBankPeriodV1beta1PeriodQueryDenomsMetadataResponse {
    /// metadata provides the client information for all the registered tokens.
    #[serde(rename = "metadatas", skip_serializing_if = "Option::is_none")]
    pub metadatas: Option<Vec<crate::models::CosmosPeriodBankPeriodV1beta1PeriodMetadata>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodBankPeriodV1beta1PeriodQueryDenomsMetadataResponse {
    /// QueryDenomsMetadataResponse is the response type for the Query/DenomsMetadata RPC method.
    pub fn new() -> CosmosPeriodBankPeriodV1beta1PeriodQueryDenomsMetadataResponse {
        CosmosPeriodBankPeriodV1beta1PeriodQueryDenomsMetadataResponse {
            metadatas: None,
            pagination: None,
        }
    }
}


