/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodMintPeriodV1beta1PeriodQueryInflationResponse : QueryInflationResponse is the response type for the Query/Inflation RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodMintPeriodV1beta1PeriodQueryInflationResponse {
    /// inflation is the current minting inflation value.
    #[serde(rename = "inflation", skip_serializing_if = "Option::is_none")]
    pub inflation: Option<String>,
}

impl CosmosPeriodMintPeriodV1beta1PeriodQueryInflationResponse {
    /// QueryInflationResponse is the response type for the Query/Inflation RPC method.
    pub fn new() -> CosmosPeriodMintPeriodV1beta1PeriodQueryInflationResponse {
        CosmosPeriodMintPeriodV1beta1PeriodQueryInflationResponse {
            inflation: None,
        }
    }
}


