/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodUpgradePeriodV1beta1PeriodQueryModuleVersionsResponse : QueryModuleVersionsResponse is the response type for the Query/ModuleVersions RPC method.  Since: cosmos-sdk 0.43



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodUpgradePeriodV1beta1PeriodQueryModuleVersionsResponse {
    /// module_versions is a list of module names with their consensus versions.
    #[serde(rename = "moduleVersions", skip_serializing_if = "Option::is_none")]
    pub module_versions: Option<Vec<crate::models::CosmosPeriodUpgradePeriodV1beta1PeriodModuleVersion>>,
}

impl CosmosPeriodUpgradePeriodV1beta1PeriodQueryModuleVersionsResponse {
    /// QueryModuleVersionsResponse is the response type for the Query/ModuleVersions RPC method.  Since: cosmos-sdk 0.43
    pub fn new() -> CosmosPeriodUpgradePeriodV1beta1PeriodQueryModuleVersionsResponse {
        CosmosPeriodUpgradePeriodV1beta1PeriodQueryModuleVersionsResponse {
            module_versions: None,
        }
    }
}


