/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGroupPeriodV1PeriodQueryGroupInfoResponse : QueryGroupInfoResponse is the Query/GroupInfo response type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGroupPeriodV1PeriodQueryGroupInfoResponse {
    #[serde(rename = "info", skip_serializing_if = "Option::is_none")]
    pub info: Option<Box<crate::models::CosmosPeriodGroupPeriodV1PeriodGroupInfo>>,
}

impl CosmosPeriodGroupPeriodV1PeriodQueryGroupInfoResponse {
    /// QueryGroupInfoResponse is the Query/GroupInfo response type.
    pub fn new() -> CosmosPeriodGroupPeriodV1PeriodQueryGroupInfoResponse {
        CosmosPeriodGroupPeriodV1PeriodQueryGroupInfoResponse {
            info: None,
        }
    }
}


