/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodDistributionPeriodV1beta1PeriodDelegationDelegatorReward : DelegationDelegatorReward represents the properties of a delegator's delegation reward.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodDistributionPeriodV1beta1PeriodDelegationDelegatorReward {
    #[serde(rename = "validatorAddress", skip_serializing_if = "Option::is_none")]
    pub validator_address: Option<String>,
    #[serde(rename = "reward", skip_serializing_if = "Option::is_none")]
    pub reward: Option<Vec<crate::models::CosmosPeriodBasePeriodV1beta1PeriodDecCoin>>,
}

impl CosmosPeriodDistributionPeriodV1beta1PeriodDelegationDelegatorReward {
    /// DelegationDelegatorReward represents the properties of a delegator's delegation reward.
    pub fn new() -> CosmosPeriodDistributionPeriodV1beta1PeriodDelegationDelegatorReward {
        CosmosPeriodDistributionPeriodV1beta1PeriodDelegationDelegatorReward {
            validator_address: None,
            reward: None,
        }
    }
}


