/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodStakingPeriodV1beta1PeriodUnbondingDelegation : UnbondingDelegation stores all of a single delegator's unbonding bonds for a single validator in an time-ordered list.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodStakingPeriodV1beta1PeriodUnbondingDelegation {
    /// delegator_address is the bech32-encoded address of the delegator.
    #[serde(rename = "delegatorAddress", skip_serializing_if = "Option::is_none")]
    pub delegator_address: Option<String>,
    /// validator_address is the bech32-encoded address of the validator.
    #[serde(rename = "validatorAddress", skip_serializing_if = "Option::is_none")]
    pub validator_address: Option<String>,
    /// entries are the unbonding delegation entries.  unbonding delegation entries
    #[serde(rename = "entries", skip_serializing_if = "Option::is_none")]
    pub entries: Option<Vec<crate::models::CosmosPeriodStakingPeriodV1beta1PeriodUnbondingDelegationEntry>>,
}

impl CosmosPeriodStakingPeriodV1beta1PeriodUnbondingDelegation {
    /// UnbondingDelegation stores all of a single delegator's unbonding bonds for a single validator in an time-ordered list.
    pub fn new() -> CosmosPeriodStakingPeriodV1beta1PeriodUnbondingDelegation {
        CosmosPeriodStakingPeriodV1beta1PeriodUnbondingDelegation {
            delegator_address: None,
            validator_address: None,
            entries: None,
        }
    }
}


