/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodEvidencePeriodV1beta1PeriodQueryAllEvidenceResponse : QueryAllEvidenceResponse is the response type for the Query/AllEvidence RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodEvidencePeriodV1beta1PeriodQueryAllEvidenceResponse {
    /// evidence returns all evidences.
    #[serde(rename = "evidence", skip_serializing_if = "Option::is_none")]
    pub evidence: Option<Vec<crate::models::GooglePeriodProtobufPeriodAny>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodEvidencePeriodV1beta1PeriodQueryAllEvidenceResponse {
    /// QueryAllEvidenceResponse is the response type for the Query/AllEvidence RPC method.
    pub fn new() -> CosmosPeriodEvidencePeriodV1beta1PeriodQueryAllEvidenceResponse {
        CosmosPeriodEvidencePeriodV1beta1PeriodQueryAllEvidenceResponse {
            evidence: None,
            pagination: None,
        }
    }
}


