/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodStakingPeriodV1beta1PeriodMsgBeginRedelegateResponse : MsgBeginRedelegateResponse defines the Msg/BeginRedelegate response type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodStakingPeriodV1beta1PeriodMsgBeginRedelegateResponse {
    #[serde(rename = "completionTime", skip_serializing_if = "Option::is_none")]
    pub completion_time: Option<String>,
}

impl CosmosPeriodStakingPeriodV1beta1PeriodMsgBeginRedelegateResponse {
    /// MsgBeginRedelegateResponse defines the Msg/BeginRedelegate response type.
    pub fn new() -> CosmosPeriodStakingPeriodV1beta1PeriodMsgBeginRedelegateResponse {
        CosmosPeriodStakingPeriodV1beta1PeriodMsgBeginRedelegateResponse {
            completion_time: None,
        }
    }
}


