/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodSlashingPeriodV1beta1PeriodParams : Params represents the parameters used for by the slashing module.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodSlashingPeriodV1beta1PeriodParams {
    #[serde(rename = "signedBlocksWindow", skip_serializing_if = "Option::is_none")]
    pub signed_blocks_window: Option<String>,
    #[serde(rename = "minSignedPerWindow", skip_serializing_if = "Option::is_none")]
    pub min_signed_per_window: Option<String>,
    #[serde(rename = "downtimeJailDuration", skip_serializing_if = "Option::is_none")]
    pub downtime_jail_duration: Option<String>,
    #[serde(rename = "slashFractionDoubleSign", skip_serializing_if = "Option::is_none")]
    pub slash_fraction_double_sign: Option<String>,
    #[serde(rename = "slashFractionDowntime", skip_serializing_if = "Option::is_none")]
    pub slash_fraction_downtime: Option<String>,
}

impl CosmosPeriodSlashingPeriodV1beta1PeriodParams {
    /// Params represents the parameters used for by the slashing module.
    pub fn new() -> CosmosPeriodSlashingPeriodV1beta1PeriodParams {
        CosmosPeriodSlashingPeriodV1beta1PeriodParams {
            signed_blocks_window: None,
            min_signed_per_window: None,
            downtime_jail_duration: None,
            slash_fraction_double_sign: None,
            slash_fraction_downtime: None,
        }
    }
}


