/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodDistributionPeriodV1beta1PeriodQueryCommunityPoolResponse : QueryCommunityPoolResponse is the response type for the Query/CommunityPool RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodDistributionPeriodV1beta1PeriodQueryCommunityPoolResponse {
    /// pool defines community pool's coins.
    #[serde(rename = "pool", skip_serializing_if = "Option::is_none")]
    pub pool: Option<Vec<crate::models::CosmosPeriodBasePeriodV1beta1PeriodDecCoin>>,
}

impl CosmosPeriodDistributionPeriodV1beta1PeriodQueryCommunityPoolResponse {
    /// QueryCommunityPoolResponse is the response type for the Query/CommunityPool RPC method.
    pub fn new() -> CosmosPeriodDistributionPeriodV1beta1PeriodQueryCommunityPoolResponse {
        CosmosPeriodDistributionPeriodV1beta1PeriodQueryCommunityPoolResponse {
            pool: None,
        }
    }
}


