/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGovPeriodV1PeriodVotingParams : VotingParams defines the params for voting on governance proposals.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGovPeriodV1PeriodVotingParams {
    /// Length of the voting period.
    #[serde(rename = "votingPeriod", skip_serializing_if = "Option::is_none")]
    pub voting_period: Option<String>,
}

impl CosmosPeriodGovPeriodV1PeriodVotingParams {
    /// VotingParams defines the params for voting on governance proposals.
    pub fn new() -> CosmosPeriodGovPeriodV1PeriodVotingParams {
        CosmosPeriodGovPeriodV1PeriodVotingParams {
            voting_period: None,
        }
    }
}


