/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodStakingPeriodV1beta1PeriodQueryRedelegationsResponse : QueryRedelegationsResponse is response type for the Query/Redelegations RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodStakingPeriodV1beta1PeriodQueryRedelegationsResponse {
    #[serde(rename = "redelegationResponses", skip_serializing_if = "Option::is_none")]
    pub redelegation_responses: Option<Vec<crate::models::CosmosPeriodStakingPeriodV1beta1PeriodRedelegationResponse>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodStakingPeriodV1beta1PeriodQueryRedelegationsResponse {
    /// QueryRedelegationsResponse is response type for the Query/Redelegations RPC method.
    pub fn new() -> CosmosPeriodStakingPeriodV1beta1PeriodQueryRedelegationsResponse {
        CosmosPeriodStakingPeriodV1beta1PeriodQueryRedelegationsResponse {
            redelegation_responses: None,
            pagination: None,
        }
    }
}


