/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodFeegrantPeriodV1beta1PeriodQueryAllowancesByGranterResponse : QueryAllowancesByGranterResponse is the response type for the Query/AllowancesByGranter RPC method.  Since: cosmos-sdk 0.46



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodFeegrantPeriodV1beta1PeriodQueryAllowancesByGranterResponse {
    /// allowances that have been issued by the granter.
    #[serde(rename = "allowances", skip_serializing_if = "Option::is_none")]
    pub allowances: Option<Vec<crate::models::CosmosPeriodFeegrantPeriodV1beta1PeriodGrant>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodFeegrantPeriodV1beta1PeriodQueryAllowancesByGranterResponse {
    /// QueryAllowancesByGranterResponse is the response type for the Query/AllowancesByGranter RPC method.  Since: cosmos-sdk 0.46
    pub fn new() -> CosmosPeriodFeegrantPeriodV1beta1PeriodQueryAllowancesByGranterResponse {
        CosmosPeriodFeegrantPeriodV1beta1PeriodQueryAllowancesByGranterResponse {
            allowances: None,
            pagination: None,
        }
    }
}


