/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodParamsPeriodV1beta1PeriodQuerySubspacesResponse : QuerySubspacesResponse defines the response types for querying for all registered subspaces and all keys for a subspace.  Since: cosmos-sdk 0.46



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodParamsPeriodV1beta1PeriodQuerySubspacesResponse {
    #[serde(rename = "subspaces", skip_serializing_if = "Option::is_none")]
    pub subspaces: Option<Vec<crate::models::CosmosPeriodParamsPeriodV1beta1PeriodSubspace>>,
}

impl CosmosPeriodParamsPeriodV1beta1PeriodQuerySubspacesResponse {
    /// QuerySubspacesResponse defines the response types for querying for all registered subspaces and all keys for a subspace.  Since: cosmos-sdk 0.46
    pub fn new() -> CosmosPeriodParamsPeriodV1beta1PeriodQuerySubspacesResponse {
        CosmosPeriodParamsPeriodV1beta1PeriodQuerySubspacesResponse {
            subspaces: None,
        }
    }
}


