/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodSlashingPeriodV1beta1PeriodQuerySigningInfosResponse {
    #[serde(rename = "info", skip_serializing_if = "Option::is_none")]
    pub info: Option<Vec<crate::models::CosmosPeriodSlashingPeriodV1beta1PeriodValidatorSigningInfo>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodSlashingPeriodV1beta1PeriodQuerySigningInfosResponse {
    pub fn new() -> CosmosPeriodSlashingPeriodV1beta1PeriodQuerySigningInfosResponse {
        CosmosPeriodSlashingPeriodV1beta1PeriodQuerySigningInfosResponse {
            info: None,
            pagination: None,
        }
    }
}


