/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodBankPeriodV1beta1PeriodMetadata : Metadata represents a struct that describes a basic token.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBankPeriodV1beta1PeriodMetadata {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "denomUnits", skip_serializing_if = "Option::is_none")]
    pub denom_units: Option<Vec<crate::models::CosmosPeriodBankPeriodV1beta1PeriodDenomUnit>>,
    /// base represents the base denom (should be the DenomUnit with exponent = 0).
    #[serde(rename = "base", skip_serializing_if = "Option::is_none")]
    pub base: Option<String>,
    /// display indicates the suggested denom that should be displayed in clients.
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    /// Since: cosmos-sdk 0.43
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// symbol is the token symbol usually shown on exchanges (eg: ATOM). This can be the same as the display.  Since: cosmos-sdk 0.43
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// URI to a document (on or off-chain) that contains additional information. Optional.  Since: cosmos-sdk 0.46
    #[serde(rename = "uri", skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    /// URIHash is a sha256 hash of a document pointed by URI. It's used to verify that the document didn't change. Optional.  Since: cosmos-sdk 0.46
    #[serde(rename = "uriHash", skip_serializing_if = "Option::is_none")]
    pub uri_hash: Option<String>,
}

impl CosmosPeriodBankPeriodV1beta1PeriodMetadata {
    /// Metadata represents a struct that describes a basic token.
    pub fn new() -> CosmosPeriodBankPeriodV1beta1PeriodMetadata {
        CosmosPeriodBankPeriodV1beta1PeriodMetadata {
            description: None,
            denom_units: None,
            base: None,
            display: None,
            name: None,
            symbol: None,
            uri: None,
            uri_hash: None,
        }
    }
}


