/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodTxPeriodV1beta1PeriodModeInfo : ModeInfo describes the signing mode of a single or nested multisig signer.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodTxPeriodV1beta1PeriodModeInfo {
    #[serde(rename = "single", skip_serializing_if = "Option::is_none")]
    pub single: Option<Box<crate::models::CosmosPeriodTxPeriodV1beta1PeriodModeInfoPeriodSingle>>,
    #[serde(rename = "multi", skip_serializing_if = "Option::is_none")]
    pub multi: Option<Box<crate::models::CosmosPeriodTxPeriodV1beta1PeriodModeInfoPeriodMulti>>,
}

impl CosmosPeriodTxPeriodV1beta1PeriodModeInfo {
    /// ModeInfo describes the signing mode of a single or nested multisig signer.
    pub fn new() -> CosmosPeriodTxPeriodV1beta1PeriodModeInfo {
        CosmosPeriodTxPeriodV1beta1PeriodModeInfo {
            single: None,
            multi: None,
        }
    }
}


