/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodVestingPeriodV1beta1PeriodPeriod : Period defines a length of time and amount of coins that will vest.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodVestingPeriodV1beta1PeriodPeriod {
    /// Period duration in seconds.
    #[serde(rename = "length", skip_serializing_if = "Option::is_none")]
    pub length: Option<String>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<Vec<crate::models::CosmosPeriodBasePeriodV1beta1PeriodCoin>>,
}

impl CosmosPeriodVestingPeriodV1beta1PeriodPeriod {
    /// Period defines a length of time and amount of coins that will vest.
    pub fn new() -> CosmosPeriodVestingPeriodV1beta1PeriodPeriod {
        CosmosPeriodVestingPeriodV1beta1PeriodPeriod {
            length: None,
            amount: None,
        }
    }
}


