/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodInterfaceImplementerDescriptor {
    #[serde(rename = "fullname", skip_serializing_if = "Option::is_none")]
    pub fullname: Option<String>,
    #[serde(rename = "typeUrl", skip_serializing_if = "Option::is_none")]
    pub type_url: Option<String>,
}

impl CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodInterfaceImplementerDescriptor {
    pub fn new() -> CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodInterfaceImplementerDescriptor {
        CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodInterfaceImplementerDescriptor {
            fullname: None,
            type_url: None,
        }
    }
}


