/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodBankPeriodV1beta1PeriodQuerySpendableBalancesResponse : QuerySpendableBalancesResponse defines the gRPC response structure for querying an account's spendable balances.  Since: cosmos-sdk 0.46



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBankPeriodV1beta1PeriodQuerySpendableBalancesResponse {
    /// balances is the spendable balances of all the coins.
    #[serde(rename = "balances", skip_serializing_if = "Option::is_none")]
    pub balances: Option<Vec<crate::models::CosmosPeriodBasePeriodV1beta1PeriodCoin>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodBankPeriodV1beta1PeriodQuerySpendableBalancesResponse {
    /// QuerySpendableBalancesResponse defines the gRPC response structure for querying an account's spendable balances.  Since: cosmos-sdk 0.46
    pub fn new() -> CosmosPeriodBankPeriodV1beta1PeriodQuerySpendableBalancesResponse {
        CosmosPeriodBankPeriodV1beta1PeriodQuerySpendableBalancesResponse {
            balances: None,
            pagination: None,
        }
    }
}


