/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodBasePeriodAbciPeriodV1beta1PeriodStringEvent : StringEvent defines en Event object wrapper where all the attributes contain key/value pairs that are strings instead of raw bytes.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodAbciPeriodV1beta1PeriodStringEvent {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Vec<crate::models::CosmosPeriodBasePeriodAbciPeriodV1beta1PeriodAttribute>>,
}

impl CosmosPeriodBasePeriodAbciPeriodV1beta1PeriodStringEvent {
    /// StringEvent defines en Event object wrapper where all the attributes contain key/value pairs that are strings instead of raw bytes.
    pub fn new() -> CosmosPeriodBasePeriodAbciPeriodV1beta1PeriodStringEvent {
        CosmosPeriodBasePeriodAbciPeriodV1beta1PeriodStringEvent {
            r#type: None,
            attributes: None,
        }
    }
}


