/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodSlashingPeriodV1beta1PeriodValidatorSigningInfo : ValidatorSigningInfo defines a validator's signing info for monitoring their liveness activity.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodSlashingPeriodV1beta1PeriodValidatorSigningInfo {
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "startHeight", skip_serializing_if = "Option::is_none")]
    pub start_height: Option<String>,
    /// Index which is incremented each time the validator was a bonded in a block and may have signed a precommit or not. This in conjunction with the `SignedBlocksWindow` param determines the index in the `MissedBlocksBitArray`.
    #[serde(rename = "indexOffset", skip_serializing_if = "Option::is_none")]
    pub index_offset: Option<String>,
    /// Timestamp until which the validator is jailed due to liveness downtime.
    #[serde(rename = "jailedUntil", skip_serializing_if = "Option::is_none")]
    pub jailed_until: Option<String>,
    /// Whether or not a validator has been tombstoned (killed out of validator set). It is set once the validator commits an equivocation or for any other configured misbehiavor.
    #[serde(rename = "tombstoned", skip_serializing_if = "Option::is_none")]
    pub tombstoned: Option<bool>,
    /// A counter kept to avoid unnecessary array reads. Note that `Sum(MissedBlocksBitArray)` always equals `MissedBlocksCounter`.
    #[serde(rename = "missedBlocksCounter", skip_serializing_if = "Option::is_none")]
    pub missed_blocks_counter: Option<String>,
}

impl CosmosPeriodSlashingPeriodV1beta1PeriodValidatorSigningInfo {
    /// ValidatorSigningInfo defines a validator's signing info for monitoring their liveness activity.
    pub fn new() -> CosmosPeriodSlashingPeriodV1beta1PeriodValidatorSigningInfo {
        CosmosPeriodSlashingPeriodV1beta1PeriodValidatorSigningInfo {
            address: None,
            start_height: None,
            index_offset: None,
            jailed_until: None,
            tombstoned: None,
            missed_blocks_counter: None,
        }
    }
}


