/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodNftPeriodV1beta1PeriodClass : Class defines the class of the nft type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodNftPeriodV1beta1PeriodClass {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "uri", skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    #[serde(rename = "uriHash", skip_serializing_if = "Option::is_none")]
    pub uri_hash: Option<String>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<crate::models::GooglePeriodProtobufPeriodAny>,
}

impl CosmosPeriodNftPeriodV1beta1PeriodClass {
    /// Class defines the class of the nft type.
    pub fn new() -> CosmosPeriodNftPeriodV1beta1PeriodClass {
        CosmosPeriodNftPeriodV1beta1PeriodClass {
            id: None,
            name: None,
            symbol: None,
            description: None,
            uri: None,
            uri_hash: None,
            data: None,
        }
    }
}


