/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGovPeriodV1beta1PeriodQueryVoteResponse : QueryVoteResponse is the response type for the Query/Vote RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGovPeriodV1beta1PeriodQueryVoteResponse {
    #[serde(rename = "vote", skip_serializing_if = "Option::is_none")]
    pub vote: Option<Box<crate::models::CosmosPeriodGovPeriodV1beta1PeriodVote>>,
}

impl CosmosPeriodGovPeriodV1beta1PeriodQueryVoteResponse {
    /// QueryVoteResponse is the response type for the Query/Vote RPC method.
    pub fn new() -> CosmosPeriodGovPeriodV1beta1PeriodQueryVoteResponse {
        CosmosPeriodGovPeriodV1beta1PeriodQueryVoteResponse {
            vote: None,
        }
    }
}


