/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodStakingPeriodV1beta1PeriodDelegationResponse : DelegationResponse is equivalent to Delegation except that it contains a balance in addition to shares which is more suitable for client responses.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodStakingPeriodV1beta1PeriodDelegationResponse {
    #[serde(rename = "delegation", skip_serializing_if = "Option::is_none")]
    pub delegation: Option<Box<crate::models::CosmosPeriodStakingPeriodV1beta1PeriodDelegation>>,
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<Box<crate::models::CosmosPeriodBasePeriodV1beta1PeriodCoin>>,
}

impl CosmosPeriodStakingPeriodV1beta1PeriodDelegationResponse {
    /// DelegationResponse is equivalent to Delegation except that it contains a balance in addition to shares which is more suitable for client responses.
    pub fn new() -> CosmosPeriodStakingPeriodV1beta1PeriodDelegationResponse {
        CosmosPeriodStakingPeriodV1beta1PeriodDelegationResponse {
            delegation: None,
            balance: None,
        }
    }
}


