/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodBasePeriodAbciPeriodV1beta1PeriodGasInfo : GasInfo defines tx execution gas context.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodAbciPeriodV1beta1PeriodGasInfo {
    /// GasWanted is the maximum units of work we allow this tx to perform.
    #[serde(rename = "gasWanted", skip_serializing_if = "Option::is_none")]
    pub gas_wanted: Option<String>,
    /// GasUsed is the amount of gas actually consumed.
    #[serde(rename = "gasUsed", skip_serializing_if = "Option::is_none")]
    pub gas_used: Option<String>,
}

impl CosmosPeriodBasePeriodAbciPeriodV1beta1PeriodGasInfo {
    /// GasInfo defines tx execution gas context.
    pub fn new() -> CosmosPeriodBasePeriodAbciPeriodV1beta1PeriodGasInfo {
        CosmosPeriodBasePeriodAbciPeriodV1beta1PeriodGasInfo {
            gas_wanted: None,
            gas_used: None,
        }
    }
}


