/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodDistributionPeriodV1beta1PeriodQueryDelegatorWithdrawAddressResponse : QueryDelegatorWithdrawAddressResponse is the response type for the Query/DelegatorWithdrawAddress RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodDistributionPeriodV1beta1PeriodQueryDelegatorWithdrawAddressResponse {
    /// withdraw_address defines the delegator address to query for.
    #[serde(rename = "withdrawAddress", skip_serializing_if = "Option::is_none")]
    pub withdraw_address: Option<String>,
}

impl CosmosPeriodDistributionPeriodV1beta1PeriodQueryDelegatorWithdrawAddressResponse {
    /// QueryDelegatorWithdrawAddressResponse is the response type for the Query/DelegatorWithdrawAddress RPC method.
    pub fn new() -> CosmosPeriodDistributionPeriodV1beta1PeriodQueryDelegatorWithdrawAddressResponse {
        CosmosPeriodDistributionPeriodV1beta1PeriodQueryDelegatorWithdrawAddressResponse {
            withdraw_address: None,
        }
    }
}


