/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodAuthzPeriodV1beta1PeriodMsgExecResponse : MsgExecResponse defines the Msg/MsgExecResponse response type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodAuthzPeriodV1beta1PeriodMsgExecResponse {
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<String>>,
}

impl CosmosPeriodAuthzPeriodV1beta1PeriodMsgExecResponse {
    /// MsgExecResponse defines the Msg/MsgExecResponse response type.
    pub fn new() -> CosmosPeriodAuthzPeriodV1beta1PeriodMsgExecResponse {
        CosmosPeriodAuthzPeriodV1beta1PeriodMsgExecResponse {
            results: None,
        }
    }
}


