/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGovPeriodV1beta1PeriodQueryProposalsResponse : QueryProposalsResponse is the response type for the Query/Proposals RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGovPeriodV1beta1PeriodQueryProposalsResponse {
    #[serde(rename = "proposals", skip_serializing_if = "Option::is_none")]
    pub proposals: Option<Vec<crate::models::CosmosPeriodGovPeriodV1beta1PeriodProposal>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodGovPeriodV1beta1PeriodQueryProposalsResponse {
    /// QueryProposalsResponse is the response type for the Query/Proposals RPC method.
    pub fn new() -> CosmosPeriodGovPeriodV1beta1PeriodQueryProposalsResponse {
        CosmosPeriodGovPeriodV1beta1PeriodQueryProposalsResponse {
            proposals: None,
            pagination: None,
        }
    }
}


