/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGovPeriodV1PeriodQueryDepositResponse : QueryDepositResponse is the response type for the Query/Deposit RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGovPeriodV1PeriodQueryDepositResponse {
    #[serde(rename = "deposit", skip_serializing_if = "Option::is_none")]
    pub deposit: Option<Box<crate::models::CosmosPeriodGovPeriodV1PeriodDeposit>>,
}

impl CosmosPeriodGovPeriodV1PeriodQueryDepositResponse {
    /// QueryDepositResponse is the response type for the Query/Deposit RPC method.
    pub fn new() -> CosmosPeriodGovPeriodV1PeriodQueryDepositResponse {
        CosmosPeriodGovPeriodV1PeriodQueryDepositResponse {
            deposit: None,
        }
    }
}


