/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodStakingPeriodV1beta1PeriodQueryDelegationResponse : QueryDelegationResponse is response type for the Query/Delegation RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodStakingPeriodV1beta1PeriodQueryDelegationResponse {
    #[serde(rename = "delegationResponse", skip_serializing_if = "Option::is_none")]
    pub delegation_response: Option<Box<crate::models::CosmosPeriodStakingPeriodV1beta1PeriodDelegationResponse>>,
}

impl CosmosPeriodStakingPeriodV1beta1PeriodQueryDelegationResponse {
    /// QueryDelegationResponse is response type for the Query/Delegation RPC method.
    pub fn new() -> CosmosPeriodStakingPeriodV1beta1PeriodQueryDelegationResponse {
        CosmosPeriodStakingPeriodV1beta1PeriodQueryDelegationResponse {
            delegation_response: None,
        }
    }
}


