/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGroupPeriodV1PeriodVoteOption : VoteOption enumerates the valid vote options for a given proposal.   - VOTE_OPTION_UNSPECIFIED: VOTE_OPTION_UNSPECIFIED defines an unspecified vote option which will return an error.  - VOTE_OPTION_YES: VOTE_OPTION_YES defines a yes vote option.  - VOTE_OPTION_ABSTAIN: VOTE_OPTION_ABSTAIN defines an abstain vote option.  - VOTE_OPTION_NO: VOTE_OPTION_NO defines a no vote option.  - VOTE_OPTION_NO_WITH_VETO: VOTE_OPTION_NO_WITH_VETO defines a no with veto vote option.

/// VoteOption enumerates the valid vote options for a given proposal.   - VOTE_OPTION_UNSPECIFIED: VOTE_OPTION_UNSPECIFIED defines an unspecified vote option which will return an error.  - VOTE_OPTION_YES: VOTE_OPTION_YES defines a yes vote option.  - VOTE_OPTION_ABSTAIN: VOTE_OPTION_ABSTAIN defines an abstain vote option.  - VOTE_OPTION_NO: VOTE_OPTION_NO defines a no vote option.  - VOTE_OPTION_NO_WITH_VETO: VOTE_OPTION_NO_WITH_VETO defines a no with veto vote option.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CosmosPeriodGroupPeriodV1PeriodVoteOption {
    #[serde(rename = "VOTE_OPTION_UNSPECIFIED")]
    Unspecified,
    #[serde(rename = "VOTE_OPTION_YES")]
    Yes,
    #[serde(rename = "VOTE_OPTION_ABSTAIN")]
    Abstain,
    #[serde(rename = "VOTE_OPTION_NO")]
    No,
    #[serde(rename = "VOTE_OPTION_NO_WITH_VETO")]
    NoWithVeto,

}

impl ToString for CosmosPeriodGroupPeriodV1PeriodVoteOption {
    fn to_string(&self) -> String {
        match self {
            Self::Unspecified => String::from("VOTE_OPTION_UNSPECIFIED"),
            Self::Yes => String::from("VOTE_OPTION_YES"),
            Self::Abstain => String::from("VOTE_OPTION_ABSTAIN"),
            Self::No => String::from("VOTE_OPTION_NO"),
            Self::NoWithVeto => String::from("VOTE_OPTION_NO_WITH_VETO"),
        }
    }
}

impl Default for CosmosPeriodGroupPeriodV1PeriodVoteOption {
    fn default() -> CosmosPeriodGroupPeriodV1PeriodVoteOption {
        Self::Unspecified
    }
}




