/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGroupPeriodV1PeriodQueryGroupMembersResponse : QueryGroupMembersResponse is the Query/GroupMembersResponse response type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGroupPeriodV1PeriodQueryGroupMembersResponse {
    /// members are the members of the group with given group_id.
    #[serde(rename = "members", skip_serializing_if = "Option::is_none")]
    pub members: Option<Vec<crate::models::CosmosPeriodGroupPeriodV1PeriodGroupMember>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodGroupPeriodV1PeriodQueryGroupMembersResponse {
    /// QueryGroupMembersResponse is the Query/GroupMembersResponse response type.
    pub fn new() -> CosmosPeriodGroupPeriodV1PeriodQueryGroupMembersResponse {
        CosmosPeriodGroupPeriodV1PeriodQueryGroupMembersResponse {
            members: None,
            pagination: None,
        }
    }
}


