/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodTxPeriodV1beta1PeriodGetBlockWithTxsResponse : GetBlockWithTxsResponse is the response type for the Service.GetBlockWithTxs method.  Since: cosmos-sdk 0.45.2



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodTxPeriodV1beta1PeriodGetBlockWithTxsResponse {
    /// txs are the transactions in the block.
    #[serde(rename = "txs", skip_serializing_if = "Option::is_none")]
    pub txs: Option<Vec<crate::models::CosmosPeriodTxPeriodV1beta1PeriodTx>>,
    #[serde(rename = "blockId", skip_serializing_if = "Option::is_none")]
    pub block_id: Option<Box<crate::models::TendermintPeriodTypesPeriodBlockId>>,
    #[serde(rename = "block", skip_serializing_if = "Option::is_none")]
    pub block: Option<Box<crate::models::TendermintPeriodTypesPeriodBlock>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodTxPeriodV1beta1PeriodGetBlockWithTxsResponse {
    /// GetBlockWithTxsResponse is the response type for the Service.GetBlockWithTxs method.  Since: cosmos-sdk 0.45.2
    pub fn new() -> CosmosPeriodTxPeriodV1beta1PeriodGetBlockWithTxsResponse {
        CosmosPeriodTxPeriodV1beta1PeriodGetBlockWithTxsResponse {
            txs: None,
            block_id: None,
            block: None,
            pagination: None,
        }
    }
}


