/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodTxPeriodV1beta1PeriodBroadcastTxResponse : BroadcastTxResponse is the response type for the Service.BroadcastTx method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodTxPeriodV1beta1PeriodBroadcastTxResponse {
    #[serde(rename = "txResponse", skip_serializing_if = "Option::is_none")]
    pub tx_response: Option<Box<crate::models::CosmosPeriodBasePeriodAbciPeriodV1beta1PeriodTxResponse>>,
}

impl CosmosPeriodTxPeriodV1beta1PeriodBroadcastTxResponse {
    /// BroadcastTxResponse is the response type for the Service.BroadcastTx method.
    pub fn new() -> CosmosPeriodTxPeriodV1beta1PeriodBroadcastTxResponse {
        CosmosPeriodTxPeriodV1beta1PeriodBroadcastTxResponse {
            tx_response: None,
        }
    }
}


