/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodStakingPeriodV1beta1PeriodCommissionRates : CommissionRates defines the initial commission rates to be used for creating a validator.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodStakingPeriodV1beta1PeriodCommissionRates {
    /// rate is the commission rate charged to delegators, as a fraction.
    #[serde(rename = "rate", skip_serializing_if = "Option::is_none")]
    pub rate: Option<String>,
    /// max_rate defines the maximum commission rate which validator can ever charge, as a fraction.
    #[serde(rename = "maxRate", skip_serializing_if = "Option::is_none")]
    pub max_rate: Option<String>,
    /// max_change_rate defines the maximum daily increase of the validator commission, as a fraction.
    #[serde(rename = "maxChangeRate", skip_serializing_if = "Option::is_none")]
    pub max_change_rate: Option<String>,
}

impl CosmosPeriodStakingPeriodV1beta1PeriodCommissionRates {
    /// CommissionRates defines the initial commission rates to be used for creating a validator.
    pub fn new() -> CosmosPeriodStakingPeriodV1beta1PeriodCommissionRates {
        CosmosPeriodStakingPeriodV1beta1PeriodCommissionRates {
            rate: None,
            max_rate: None,
            max_change_rate: None,
        }
    }
}


