/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodInterfaceDescriptor {
    #[serde(rename = "fullname", skip_serializing_if = "Option::is_none")]
    pub fullname: Option<String>,
    #[serde(rename = "interfaceAcceptingMessages", skip_serializing_if = "Option::is_none")]
    pub interface_accepting_messages: Option<Vec<crate::models::CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodInterfaceAcceptingMessageDescriptor>>,
    #[serde(rename = "interfaceImplementers", skip_serializing_if = "Option::is_none")]
    pub interface_implementers: Option<Vec<crate::models::CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodInterfaceImplementerDescriptor>>,
}

impl CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodInterfaceDescriptor {
    pub fn new() -> CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodInterfaceDescriptor {
        CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodInterfaceDescriptor {
            fullname: None,
            interface_accepting_messages: None,
            interface_implementers: None,
        }
    }
}


