/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodNftPeriodV1beta1PeriodQueryClassesResponse {
    #[serde(rename = "classes", skip_serializing_if = "Option::is_none")]
    pub classes: Option<Vec<crate::models::CosmosPeriodNftPeriodV1beta1PeriodClass>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodNftPeriodV1beta1PeriodQueryClassesResponse {
    pub fn new() -> CosmosPeriodNftPeriodV1beta1PeriodQueryClassesResponse {
        CosmosPeriodNftPeriodV1beta1PeriodQueryClassesResponse {
            classes: None,
            pagination: None,
        }
    }
}


