/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodBankPeriodV1beta1PeriodQueryDenomOwnersResponse : QueryDenomOwnersResponse defines the RPC response of a DenomOwners RPC query.  Since: cosmos-sdk 0.46



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBankPeriodV1beta1PeriodQueryDenomOwnersResponse {
    #[serde(rename = "denomOwners", skip_serializing_if = "Option::is_none")]
    pub denom_owners: Option<Vec<crate::models::CosmosPeriodBankPeriodV1beta1PeriodDenomOwner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodBankPeriodV1beta1PeriodQueryDenomOwnersResponse {
    /// QueryDenomOwnersResponse defines the RPC response of a DenomOwners RPC query.  Since: cosmos-sdk 0.46
    pub fn new() -> CosmosPeriodBankPeriodV1beta1PeriodQueryDenomOwnersResponse {
        CosmosPeriodBankPeriodV1beta1PeriodQueryDenomOwnersResponse {
            denom_owners: None,
            pagination: None,
        }
    }
}


