/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodAuthPeriodV1beta1PeriodBech32PrefixResponse : Bech32PrefixResponse is the response type for Bech32Prefix rpc method.  Since: cosmos-sdk 0.46



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodAuthPeriodV1beta1PeriodBech32PrefixResponse {
    #[serde(rename = "bech32Prefix", skip_serializing_if = "Option::is_none")]
    pub bech32_prefix: Option<String>,
}

impl CosmosPeriodAuthPeriodV1beta1PeriodBech32PrefixResponse {
    /// Bech32PrefixResponse is the response type for Bech32Prefix rpc method.  Since: cosmos-sdk 0.46
    pub fn new() -> CosmosPeriodAuthPeriodV1beta1PeriodBech32PrefixResponse {
        CosmosPeriodAuthPeriodV1beta1PeriodBech32PrefixResponse {
            bech32_prefix: None,
        }
    }
}


