/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGroupPeriodV1PeriodVote : Vote represents a vote for a proposal.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGroupPeriodV1PeriodVote {
    /// proposal is the unique ID of the proposal.
    #[serde(rename = "proposalId", skip_serializing_if = "Option::is_none")]
    pub proposal_id: Option<String>,
    /// voter is the account address of the voter.
    #[serde(rename = "voter", skip_serializing_if = "Option::is_none")]
    pub voter: Option<String>,
    #[serde(rename = "option", skip_serializing_if = "Option::is_none")]
    pub option: Option<crate::models::CosmosPeriodGroupPeriodV1PeriodVoteOption>,
    /// metadata is any arbitrary metadata to attached to the vote.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<String>,
    /// submit_time is the timestamp when the vote was submitted.
    #[serde(rename = "submitTime", skip_serializing_if = "Option::is_none")]
    pub submit_time: Option<String>,
}

impl CosmosPeriodGroupPeriodV1PeriodVote {
    /// Vote represents a vote for a proposal.
    pub fn new() -> CosmosPeriodGroupPeriodV1PeriodVote {
        CosmosPeriodGroupPeriodV1PeriodVote {
            proposal_id: None,
            voter: None,
            option: None,
            metadata: None,
            submit_time: None,
        }
    }
}


