/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodBlock : Block is tendermint type Block, with the Header proposer address field converted to bech32 string.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodBlock {
    #[serde(rename = "header", skip_serializing_if = "Option::is_none")]
    pub header: Option<Box<crate::models::CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodHeader>>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::TendermintPeriodTypesPeriodData>>,
    #[serde(rename = "evidence", skip_serializing_if = "Option::is_none")]
    pub evidence: Option<Box<crate::models::TendermintPeriodTypesPeriodEvidenceList>>,
    #[serde(rename = "lastCommit", skip_serializing_if = "Option::is_none")]
    pub last_commit: Option<Box<crate::models::TendermintPeriodTypesPeriodCommit>>,
}

impl CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodBlock {
    /// Block is tendermint type Block, with the Header proposer address field converted to bech32 string.
    pub fn new() -> CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodBlock {
        CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodBlock {
            header: None,
            data: None,
            evidence: None,
            last_commit: None,
        }
    }
}


