/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGroupPeriodV1PeriodQueryGroupPoliciesByGroupResponse : QueryGroupPoliciesByGroupResponse is the Query/GroupPoliciesByGroup response type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGroupPeriodV1PeriodQueryGroupPoliciesByGroupResponse {
    /// group_policies are the group policies info associated with the provided group.
    #[serde(rename = "groupPolicies", skip_serializing_if = "Option::is_none")]
    pub group_policies: Option<Vec<crate::models::CosmosPeriodGroupPeriodV1PeriodGroupPolicyInfo>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodGroupPeriodV1PeriodQueryGroupPoliciesByGroupResponse {
    /// QueryGroupPoliciesByGroupResponse is the Query/GroupPoliciesByGroup response type.
    pub fn new() -> CosmosPeriodGroupPeriodV1PeriodQueryGroupPoliciesByGroupResponse {
        CosmosPeriodGroupPeriodV1PeriodQueryGroupPoliciesByGroupResponse {
            group_policies: None,
            pagination: None,
        }
    }
}


