/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodGetSyncingResponse : GetSyncingResponse is the response type for the Query/GetSyncing RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodGetSyncingResponse {
    #[serde(rename = "syncing", skip_serializing_if = "Option::is_none")]
    pub syncing: Option<bool>,
}

impl CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodGetSyncingResponse {
    /// GetSyncingResponse is the response type for the Query/GetSyncing RPC method.
    pub fn new() -> CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodGetSyncingResponse {
        CosmosPeriodBasePeriodTendermintPeriodV1beta1PeriodGetSyncingResponse {
            syncing: None,
        }
    }
}


