/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodAppPeriodV1alpha1PeriodQueryConfigResponse : QueryConfigRequest is the Query/Config response type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodAppPeriodV1alpha1PeriodQueryConfigResponse {
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<Box<crate::models::CosmosPeriodAppPeriodV1alpha1PeriodConfig>>,
}

impl CosmosPeriodAppPeriodV1alpha1PeriodQueryConfigResponse {
    /// QueryConfigRequest is the Query/Config response type.
    pub fn new() -> CosmosPeriodAppPeriodV1alpha1PeriodQueryConfigResponse {
        CosmosPeriodAppPeriodV1alpha1PeriodQueryConfigResponse {
            config: None,
        }
    }
}


