/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodDistributionPeriodV1beta1PeriodQueryValidatorCommissionResponse {
    #[serde(rename = "commission", skip_serializing_if = "Option::is_none")]
    pub commission: Option<Box<crate::models::CosmosPeriodDistributionPeriodV1beta1PeriodValidatorAccumulatedCommission>>,
}

impl CosmosPeriodDistributionPeriodV1beta1PeriodQueryValidatorCommissionResponse {
    pub fn new() -> CosmosPeriodDistributionPeriodV1beta1PeriodQueryValidatorCommissionResponse {
        CosmosPeriodDistributionPeriodV1beta1PeriodQueryValidatorCommissionResponse {
            commission: None,
        }
    }
}


