/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodDistributionPeriodV1beta1PeriodMsgWithdrawValidatorCommissionResponse : MsgWithdrawValidatorCommissionResponse defines the Msg/WithdrawValidatorCommission response type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodDistributionPeriodV1beta1PeriodMsgWithdrawValidatorCommissionResponse {
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<Vec<crate::models::CosmosPeriodBasePeriodV1beta1PeriodCoin>>,
}

impl CosmosPeriodDistributionPeriodV1beta1PeriodMsgWithdrawValidatorCommissionResponse {
    /// MsgWithdrawValidatorCommissionResponse defines the Msg/WithdrawValidatorCommission response type.
    pub fn new() -> CosmosPeriodDistributionPeriodV1beta1PeriodMsgWithdrawValidatorCommissionResponse {
        CosmosPeriodDistributionPeriodV1beta1PeriodMsgWithdrawValidatorCommissionResponse {
            amount: None,
        }
    }
}


