/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGroupPeriodV1PeriodQueryVotesByProposalResponse : QueryVotesByProposalResponse is the Query/VotesByProposal response type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGroupPeriodV1PeriodQueryVotesByProposalResponse {
    /// votes are the list of votes for given proposal_id.
    #[serde(rename = "votes", skip_serializing_if = "Option::is_none")]
    pub votes: Option<Vec<crate::models::CosmosPeriodGroupPeriodV1PeriodVote>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodGroupPeriodV1PeriodQueryVotesByProposalResponse {
    /// QueryVotesByProposalResponse is the Query/VotesByProposal response type.
    pub fn new() -> CosmosPeriodGroupPeriodV1PeriodQueryVotesByProposalResponse {
        CosmosPeriodGroupPeriodV1PeriodQueryVotesByProposalResponse {
            votes: None,
            pagination: None,
        }
    }
}


