/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodDistributionPeriodV1beta1PeriodQueryValidatorSlashesResponse : QueryValidatorSlashesResponse is the response type for the Query/ValidatorSlashes RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodDistributionPeriodV1beta1PeriodQueryValidatorSlashesResponse {
    /// slashes defines the slashes the validator received.
    #[serde(rename = "slashes", skip_serializing_if = "Option::is_none")]
    pub slashes: Option<Vec<crate::models::CosmosPeriodDistributionPeriodV1beta1PeriodValidatorSlashEvent>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodDistributionPeriodV1beta1PeriodQueryValidatorSlashesResponse {
    /// QueryValidatorSlashesResponse is the response type for the Query/ValidatorSlashes RPC method.
    pub fn new() -> CosmosPeriodDistributionPeriodV1beta1PeriodQueryValidatorSlashesResponse {
        CosmosPeriodDistributionPeriodV1beta1PeriodQueryValidatorSlashesResponse {
            slashes: None,
            pagination: None,
        }
    }
}


