/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGroupPeriodV1PeriodExec : Exec defines modes of execution of a proposal on creation or on new vote.   - EXEC_UNSPECIFIED: An empty value means that there should be a separate MsgExec request for the proposal to execute.  - EXEC_TRY: Try to execute the proposal immediately. If the proposal is not allowed per the DecisionPolicy, the proposal will still be open and could be executed at a later point.

/// Exec defines modes of execution of a proposal on creation or on new vote.   - EXEC_UNSPECIFIED: An empty value means that there should be a separate MsgExec request for the proposal to execute.  - EXEC_TRY: Try to execute the proposal immediately. If the proposal is not allowed per the DecisionPolicy, the proposal will still be open and could be executed at a later point.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CosmosPeriodGroupPeriodV1PeriodExec {
    #[serde(rename = "EXEC_UNSPECIFIED")]
    Unspecified,
    #[serde(rename = "EXEC_TRY")]
    Try,

}

impl ToString for CosmosPeriodGroupPeriodV1PeriodExec {
    fn to_string(&self) -> String {
        match self {
            Self::Unspecified => String::from("EXEC_UNSPECIFIED"),
            Self::Try => String::from("EXEC_TRY"),
        }
    }
}

impl Default for CosmosPeriodGroupPeriodV1PeriodExec {
    fn default() -> CosmosPeriodGroupPeriodV1PeriodExec {
        Self::Unspecified
    }
}




