/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodDistributionPeriodV1beta1PeriodQueryDelegationRewardsResponse : QueryDelegationRewardsResponse is the response type for the Query/DelegationRewards RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodDistributionPeriodV1beta1PeriodQueryDelegationRewardsResponse {
    /// rewards defines the rewards accrued by a delegation.
    #[serde(rename = "rewards", skip_serializing_if = "Option::is_none")]
    pub rewards: Option<Vec<crate::models::CosmosPeriodBasePeriodV1beta1PeriodDecCoin>>,
}

impl CosmosPeriodDistributionPeriodV1beta1PeriodQueryDelegationRewardsResponse {
    /// QueryDelegationRewardsResponse is the response type for the Query/DelegationRewards RPC method.
    pub fn new() -> CosmosPeriodDistributionPeriodV1beta1PeriodQueryDelegationRewardsResponse {
        CosmosPeriodDistributionPeriodV1beta1PeriodQueryDelegationRewardsResponse {
            rewards: None,
        }
    }
}


