/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodChainDescriptor {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodChainDescriptor {
    pub fn new() -> CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodChainDescriptor {
        CosmosPeriodBasePeriodReflectionPeriodV2alpha1PeriodChainDescriptor {
            id: None,
        }
    }
}


