/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGroupPeriodV1PeriodMsgExecResponse : MsgExecResponse is the Msg/Exec request type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGroupPeriodV1PeriodMsgExecResponse {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<crate::models::CosmosPeriodGroupPeriodV1PeriodProposalExecutorResult>,
}

impl CosmosPeriodGroupPeriodV1PeriodMsgExecResponse {
    /// MsgExecResponse is the Msg/Exec request type.
    pub fn new() -> CosmosPeriodGroupPeriodV1PeriodMsgExecResponse {
        CosmosPeriodGroupPeriodV1PeriodMsgExecResponse {
            result: None,
        }
    }
}


