/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodDistributionPeriodV1beta1PeriodQueryDelegatorValidatorsResponse : QueryDelegatorValidatorsResponse is the response type for the Query/DelegatorValidators RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodDistributionPeriodV1beta1PeriodQueryDelegatorValidatorsResponse {
    /// validators defines the validators a delegator is delegating for.
    #[serde(rename = "validators", skip_serializing_if = "Option::is_none")]
    pub validators: Option<Vec<String>>,
}

impl CosmosPeriodDistributionPeriodV1beta1PeriodQueryDelegatorValidatorsResponse {
    /// QueryDelegatorValidatorsResponse is the response type for the Query/DelegatorValidators RPC method.
    pub fn new() -> CosmosPeriodDistributionPeriodV1beta1PeriodQueryDelegatorValidatorsResponse {
        CosmosPeriodDistributionPeriodV1beta1PeriodQueryDelegatorValidatorsResponse {
            validators: None,
        }
    }
}


