/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodTxPeriodV1beta1PeriodAuthInfo : AuthInfo describes the fee and signer modes that are used to sign a transaction.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodTxPeriodV1beta1PeriodAuthInfo {
    /// signer_infos defines the signing modes for the required signers. The number and order of elements must match the required signers from TxBody's messages. The first element is the primary signer and the one which pays the fee.
    #[serde(rename = "signerInfos", skip_serializing_if = "Option::is_none")]
    pub signer_infos: Option<Vec<crate::models::CosmosPeriodTxPeriodV1beta1PeriodSignerInfo>>,
    #[serde(rename = "fee", skip_serializing_if = "Option::is_none")]
    pub fee: Option<Box<crate::models::CosmosPeriodTxPeriodV1beta1PeriodFee>>,
    #[serde(rename = "tip", skip_serializing_if = "Option::is_none")]
    pub tip: Option<Box<crate::models::CosmosPeriodTxPeriodV1beta1PeriodTip>>,
}

impl CosmosPeriodTxPeriodV1beta1PeriodAuthInfo {
    /// AuthInfo describes the fee and signer modes that are used to sign a transaction.
    pub fn new() -> CosmosPeriodTxPeriodV1beta1PeriodAuthInfo {
        CosmosPeriodTxPeriodV1beta1PeriodAuthInfo {
            signer_infos: None,
            fee: None,
            tip: None,
        }
    }
}


