/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodStakingPeriodV1beta1PeriodRedelegationResponse : RedelegationResponse is equivalent to a Redelegation except that its entries contain a balance in addition to shares which is more suitable for client responses.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodStakingPeriodV1beta1PeriodRedelegationResponse {
    #[serde(rename = "redelegation", skip_serializing_if = "Option::is_none")]
    pub redelegation: Option<Box<crate::models::CosmosPeriodStakingPeriodV1beta1PeriodRedelegation>>,
    #[serde(rename = "entries", skip_serializing_if = "Option::is_none")]
    pub entries: Option<Vec<crate::models::CosmosPeriodStakingPeriodV1beta1PeriodRedelegationEntryResponse>>,
}

impl CosmosPeriodStakingPeriodV1beta1PeriodRedelegationResponse {
    /// RedelegationResponse is equivalent to a Redelegation except that its entries contain a balance in addition to shares which is more suitable for client responses.
    pub fn new() -> CosmosPeriodStakingPeriodV1beta1PeriodRedelegationResponse {
        CosmosPeriodStakingPeriodV1beta1PeriodRedelegationResponse {
            redelegation: None,
            entries: None,
        }
    }
}


