/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGovPeriodV1beta1PeriodMsgSubmitProposalResponse : MsgSubmitProposalResponse defines the Msg/SubmitProposal response type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGovPeriodV1beta1PeriodMsgSubmitProposalResponse {
    #[serde(rename = "proposalId", skip_serializing_if = "Option::is_none")]
    pub proposal_id: Option<String>,
}

impl CosmosPeriodGovPeriodV1beta1PeriodMsgSubmitProposalResponse {
    /// MsgSubmitProposalResponse defines the Msg/SubmitProposal response type.
    pub fn new() -> CosmosPeriodGovPeriodV1beta1PeriodMsgSubmitProposalResponse {
        CosmosPeriodGovPeriodV1beta1PeriodMsgSubmitProposalResponse {
            proposal_id: None,
        }
    }
}


