/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodAuthzPeriodV1beta1PeriodGrant : Grant gives permissions to execute the provide method with expiration time.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodAuthzPeriodV1beta1PeriodGrant {
    #[serde(rename = "authorization", skip_serializing_if = "Option::is_none")]
    pub authorization: Option<crate::models::GooglePeriodProtobufPeriodAny>,
    #[serde(rename = "expiration", skip_serializing_if = "Option::is_none")]
    pub expiration: Option<String>,
}

impl CosmosPeriodAuthzPeriodV1beta1PeriodGrant {
    /// Grant gives permissions to execute the provide method with expiration time.
    pub fn new() -> CosmosPeriodAuthzPeriodV1beta1PeriodGrant {
        CosmosPeriodAuthzPeriodV1beta1PeriodGrant {
            authorization: None,
            expiration: None,
        }
    }
}


