/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodTxPeriodV1beta1PeriodBroadcastMode : BroadcastMode specifies the broadcast mode for the TxService.Broadcast RPC method.   - BROADCAST_MODE_UNSPECIFIED: zero-value for mode ordering  - BROADCAST_MODE_BLOCK: BROADCAST_MODE_BLOCK defines a tx broadcasting mode where the client waits for the tx to be committed in a block.  - BROADCAST_MODE_SYNC: BROADCAST_MODE_SYNC defines a tx broadcasting mode where the client waits for a CheckTx execution response only.  - BROADCAST_MODE_ASYNC: BROADCAST_MODE_ASYNC defines a tx broadcasting mode where the client returns immediately.

/// BroadcastMode specifies the broadcast mode for the TxService.Broadcast RPC method.   - BROADCAST_MODE_UNSPECIFIED: zero-value for mode ordering  - BROADCAST_MODE_BLOCK: BROADCAST_MODE_BLOCK defines a tx broadcasting mode where the client waits for the tx to be committed in a block.  - BROADCAST_MODE_SYNC: BROADCAST_MODE_SYNC defines a tx broadcasting mode where the client waits for a CheckTx execution response only.  - BROADCAST_MODE_ASYNC: BROADCAST_MODE_ASYNC defines a tx broadcasting mode where the client returns immediately.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CosmosPeriodTxPeriodV1beta1PeriodBroadcastMode {
    #[serde(rename = "BROADCAST_MODE_UNSPECIFIED")]
    Unspecified,
    #[serde(rename = "BROADCAST_MODE_BLOCK")]
    Block,
    #[serde(rename = "BROADCAST_MODE_SYNC")]
    Sync,
    #[serde(rename = "BROADCAST_MODE_ASYNC")]
    Async,

}

impl ToString for CosmosPeriodTxPeriodV1beta1PeriodBroadcastMode {
    fn to_string(&self) -> String {
        match self {
            Self::Unspecified => String::from("BROADCAST_MODE_UNSPECIFIED"),
            Self::Block => String::from("BROADCAST_MODE_BLOCK"),
            Self::Sync => String::from("BROADCAST_MODE_SYNC"),
            Self::Async => String::from("BROADCAST_MODE_ASYNC"),
        }
    }
}

impl Default for CosmosPeriodTxPeriodV1beta1PeriodBroadcastMode {
    fn default() -> CosmosPeriodTxPeriodV1beta1PeriodBroadcastMode {
        Self::Unspecified
    }
}




