/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGroupPeriodV1PeriodQueryGroupsResponse : QueryGroupsResponse is the Query/Groups response type.  Since: cosmos-sdk 0.47.1



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGroupPeriodV1PeriodQueryGroupsResponse {
    /// `groups` is all the groups present in state.
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Vec<crate::models::CosmosPeriodGroupPeriodV1PeriodGroupInfo>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodGroupPeriodV1PeriodQueryGroupsResponse {
    /// QueryGroupsResponse is the Query/Groups response type.  Since: cosmos-sdk 0.47.1
    pub fn new() -> CosmosPeriodGroupPeriodV1PeriodQueryGroupsResponse {
        CosmosPeriodGroupPeriodV1PeriodQueryGroupsResponse {
            groups: None,
            pagination: None,
        }
    }
}


