/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodDistributionPeriodV1beta1PeriodValidatorOutstandingRewards : ValidatorOutstandingRewards represents outstanding (un-withdrawn) rewards for a validator inexpensive to track, allows simple sanity checks.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodDistributionPeriodV1beta1PeriodValidatorOutstandingRewards {
    #[serde(rename = "rewards", skip_serializing_if = "Option::is_none")]
    pub rewards: Option<Vec<crate::models::CosmosPeriodBasePeriodV1beta1PeriodDecCoin>>,
}

impl CosmosPeriodDistributionPeriodV1beta1PeriodValidatorOutstandingRewards {
    /// ValidatorOutstandingRewards represents outstanding (un-withdrawn) rewards for a validator inexpensive to track, allows simple sanity checks.
    pub fn new() -> CosmosPeriodDistributionPeriodV1beta1PeriodValidatorOutstandingRewards {
        CosmosPeriodDistributionPeriodV1beta1PeriodValidatorOutstandingRewards {
            rewards: None,
        }
    }
}


