/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodTxPeriodV1beta1PeriodGetTxResponse : GetTxResponse is the response type for the Service.GetTx method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodTxPeriodV1beta1PeriodGetTxResponse {
    #[serde(rename = "tx", skip_serializing_if = "Option::is_none")]
    pub tx: Option<Box<crate::models::CosmosPeriodTxPeriodV1beta1PeriodTx>>,
    #[serde(rename = "txResponse", skip_serializing_if = "Option::is_none")]
    pub tx_response: Option<Box<crate::models::CosmosPeriodBasePeriodAbciPeriodV1beta1PeriodTxResponse>>,
}

impl CosmosPeriodTxPeriodV1beta1PeriodGetTxResponse {
    /// GetTxResponse is the response type for the Service.GetTx method.
    pub fn new() -> CosmosPeriodTxPeriodV1beta1PeriodGetTxResponse {
        CosmosPeriodTxPeriodV1beta1PeriodGetTxResponse {
            tx: None,
            tx_response: None,
        }
    }
}


