/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodFeegrantPeriodV1beta1PeriodGrant {
    /// granter is the address of the user granting an allowance of their funds.
    #[serde(rename = "granter", skip_serializing_if = "Option::is_none")]
    pub granter: Option<String>,
    /// grantee is the address of the user being granted an allowance of another user's funds.
    #[serde(rename = "grantee", skip_serializing_if = "Option::is_none")]
    pub grantee: Option<String>,
    #[serde(rename = "allowance", skip_serializing_if = "Option::is_none")]
    pub allowance: Option<crate::models::GooglePeriodProtobufPeriodAny>,
}

impl CosmosPeriodFeegrantPeriodV1beta1PeriodGrant {
    pub fn new() -> CosmosPeriodFeegrantPeriodV1beta1PeriodGrant {
        CosmosPeriodFeegrantPeriodV1beta1PeriodGrant {
            granter: None,
            grantee: None,
            allowance: None,
        }
    }
}


