/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodAuthPeriodV1beta1PeriodAddressStringToBytesResponse : AddressStringToBytesResponse is the response type for AddressBytes rpc method.  Since: cosmos-sdk 0.46



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodAuthPeriodV1beta1PeriodAddressStringToBytesResponse {
    #[serde(rename = "addressBytes", skip_serializing_if = "Option::is_none")]
    pub address_bytes: Option<String>,
}

impl CosmosPeriodAuthPeriodV1beta1PeriodAddressStringToBytesResponse {
    /// AddressStringToBytesResponse is the response type for AddressBytes rpc method.  Since: cosmos-sdk 0.46
    pub fn new() -> CosmosPeriodAuthPeriodV1beta1PeriodAddressStringToBytesResponse {
        CosmosPeriodAuthPeriodV1beta1PeriodAddressStringToBytesResponse {
            address_bytes: None,
        }
    }
}


