/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodEvidencePeriodV1beta1PeriodMsgSubmitEvidenceResponse : MsgSubmitEvidenceResponse defines the Msg/SubmitEvidence response type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodEvidencePeriodV1beta1PeriodMsgSubmitEvidenceResponse {
    /// hash defines the hash of the evidence.
    #[serde(rename = "hash", skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
}

impl CosmosPeriodEvidencePeriodV1beta1PeriodMsgSubmitEvidenceResponse {
    /// MsgSubmitEvidenceResponse defines the Msg/SubmitEvidence response type.
    pub fn new() -> CosmosPeriodEvidencePeriodV1beta1PeriodMsgSubmitEvidenceResponse {
        CosmosPeriodEvidencePeriodV1beta1PeriodMsgSubmitEvidenceResponse {
            hash: None,
        }
    }
}


