/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodStakingPeriodV1beta1PeriodPool : Pool is used for tracking bonded and not-bonded token supply of the bond denomination.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodStakingPeriodV1beta1PeriodPool {
    #[serde(rename = "notBondedTokens", skip_serializing_if = "Option::is_none")]
    pub not_bonded_tokens: Option<String>,
    #[serde(rename = "bondedTokens", skip_serializing_if = "Option::is_none")]
    pub bonded_tokens: Option<String>,
}

impl CosmosPeriodStakingPeriodV1beta1PeriodPool {
    /// Pool is used for tracking bonded and not-bonded token supply of the bond denomination.
    pub fn new() -> CosmosPeriodStakingPeriodV1beta1PeriodPool {
        CosmosPeriodStakingPeriodV1beta1PeriodPool {
            not_bonded_tokens: None,
            bonded_tokens: None,
        }
    }
}


