/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodNftPeriodV1beta1PeriodNft : NFT defines the NFT.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodNftPeriodV1beta1PeriodNft {
    #[serde(rename = "classId", skip_serializing_if = "Option::is_none")]
    pub class_id: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "uri", skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    #[serde(rename = "uriHash", skip_serializing_if = "Option::is_none")]
    pub uri_hash: Option<String>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<crate::models::GooglePeriodProtobufPeriodAny>,
}

impl CosmosPeriodNftPeriodV1beta1PeriodNft {
    /// NFT defines the NFT.
    pub fn new() -> CosmosPeriodNftPeriodV1beta1PeriodNft {
        CosmosPeriodNftPeriodV1beta1PeriodNft {
            class_id: None,
            id: None,
            uri: None,
            uri_hash: None,
            data: None,
        }
    }
}


