/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodStakingPeriodV1beta1PeriodBondStatus : BondStatus is the status of a validator.   - BOND_STATUS_UNSPECIFIED: UNSPECIFIED defines an invalid validator status.  - BOND_STATUS_UNBONDED: UNBONDED defines a validator that is not bonded.  - BOND_STATUS_UNBONDING: UNBONDING defines a validator that is unbonding.  - BOND_STATUS_BONDED: BONDED defines a validator that is bonded.

/// BondStatus is the status of a validator.   - BOND_STATUS_UNSPECIFIED: UNSPECIFIED defines an invalid validator status.  - BOND_STATUS_UNBONDED: UNBONDED defines a validator that is not bonded.  - BOND_STATUS_UNBONDING: UNBONDING defines a validator that is unbonding.  - BOND_STATUS_BONDED: BONDED defines a validator that is bonded.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CosmosPeriodStakingPeriodV1beta1PeriodBondStatus {
    #[serde(rename = "BOND_STATUS_UNSPECIFIED")]
    Unspecified,
    #[serde(rename = "BOND_STATUS_UNBONDED")]
    Unbonded,
    #[serde(rename = "BOND_STATUS_UNBONDING")]
    Unbonding,
    #[serde(rename = "BOND_STATUS_BONDED")]
    Bonded,

}

impl ToString for CosmosPeriodStakingPeriodV1beta1PeriodBondStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Unspecified => String::from("BOND_STATUS_UNSPECIFIED"),
            Self::Unbonded => String::from("BOND_STATUS_UNBONDED"),
            Self::Unbonding => String::from("BOND_STATUS_UNBONDING"),
            Self::Bonded => String::from("BOND_STATUS_BONDED"),
        }
    }
}

impl Default for CosmosPeriodStakingPeriodV1beta1PeriodBondStatus {
    fn default() -> CosmosPeriodStakingPeriodV1beta1PeriodBondStatus {
        Self::Unspecified
    }
}




