/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodBankPeriodV1beta1PeriodQueryBalanceResponse : QueryBalanceResponse is the response type for the Query/Balance RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBankPeriodV1beta1PeriodQueryBalanceResponse {
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<Box<crate::models::CosmosPeriodBasePeriodV1beta1PeriodCoin>>,
}

impl CosmosPeriodBankPeriodV1beta1PeriodQueryBalanceResponse {
    /// QueryBalanceResponse is the response type for the Query/Balance RPC method.
    pub fn new() -> CosmosPeriodBankPeriodV1beta1PeriodQueryBalanceResponse {
        CosmosPeriodBankPeriodV1beta1PeriodQueryBalanceResponse {
            balance: None,
        }
    }
}


