/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodGroupPeriodV1PeriodMsgCreateGroupResponse : MsgCreateGroupResponse is the Msg/CreateGroup response type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodGroupPeriodV1PeriodMsgCreateGroupResponse {
    /// group_id is the unique ID of the newly created group.
    #[serde(rename = "groupId", skip_serializing_if = "Option::is_none")]
    pub group_id: Option<String>,
}

impl CosmosPeriodGroupPeriodV1PeriodMsgCreateGroupResponse {
    /// MsgCreateGroupResponse is the Msg/CreateGroup response type.
    pub fn new() -> CosmosPeriodGroupPeriodV1PeriodMsgCreateGroupResponse {
        CosmosPeriodGroupPeriodV1PeriodMsgCreateGroupResponse {
            group_id: None,
        }
    }
}


