/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodStakingPeriodV1beta1PeriodQueryValidatorsResponse {
    /// validators contains all the queried validators.
    #[serde(rename = "validators", skip_serializing_if = "Option::is_none")]
    pub validators: Option<Vec<crate::models::CosmosPeriodStakingPeriodV1beta1PeriodValidator>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl CosmosPeriodStakingPeriodV1beta1PeriodQueryValidatorsResponse {
    pub fn new() -> CosmosPeriodStakingPeriodV1beta1PeriodQueryValidatorsResponse {
        CosmosPeriodStakingPeriodV1beta1PeriodQueryValidatorsResponse {
            validators: None,
            pagination: None,
        }
    }
}


