/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodParamsPeriodV1beta1PeriodSubspace : Subspace defines a parameter subspace name and all the keys that exist for the subspace.  Since: cosmos-sdk 0.46



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodParamsPeriodV1beta1PeriodSubspace {
    #[serde(rename = "subspace", skip_serializing_if = "Option::is_none")]
    pub subspace: Option<String>,
    #[serde(rename = "keys", skip_serializing_if = "Option::is_none")]
    pub keys: Option<Vec<String>>,
}

impl CosmosPeriodParamsPeriodV1beta1PeriodSubspace {
    /// Subspace defines a parameter subspace name and all the keys that exist for the subspace.  Since: cosmos-sdk 0.46
    pub fn new() -> CosmosPeriodParamsPeriodV1beta1PeriodSubspace {
        CosmosPeriodParamsPeriodV1beta1PeriodSubspace {
            subspace: None,
            keys: None,
        }
    }
}


