/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CosmosPeriodBasePeriodReflectionPeriodV1beta1PeriodListImplementationsResponse : ListImplementationsResponse is the response type of the ListImplementations RPC.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosPeriodBasePeriodReflectionPeriodV1beta1PeriodListImplementationsResponse {
    #[serde(rename = "implementationMessageNames", skip_serializing_if = "Option::is_none")]
    pub implementation_message_names: Option<Vec<String>>,
}

impl CosmosPeriodBasePeriodReflectionPeriodV1beta1PeriodListImplementationsResponse {
    /// ListImplementationsResponse is the response type of the ListImplementations RPC.
    pub fn new() -> CosmosPeriodBasePeriodReflectionPeriodV1beta1PeriodListImplementationsResponse {
        CosmosPeriodBasePeriodReflectionPeriodV1beta1PeriodListImplementationsResponse {
            implementation_message_names: None,
        }
    }
}


