/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EthermintPeriodEvmPeriodV1PeriodParams {
    /// evm_denom represents the token denomination used to run the EVM state transitions.
    #[serde(rename = "evmDenom", skip_serializing_if = "Option::is_none")]
    pub evm_denom: Option<String>,
    #[serde(rename = "enableCreate", skip_serializing_if = "Option::is_none")]
    pub enable_create: Option<bool>,
    #[serde(rename = "enableCall", skip_serializing_if = "Option::is_none")]
    pub enable_call: Option<bool>,
    #[serde(rename = "extraEips", skip_serializing_if = "Option::is_none")]
    pub extra_eips: Option<Vec<String>>,
    #[serde(rename = "chainConfig", skip_serializing_if = "Option::is_none")]
    pub chain_config: Option<Box<crate::models::EthermintPeriodEvmPeriodV1PeriodChainConfig>>,
    /// allow_unprotected_txs defines if replay-protected (i.e non EIP155 signed) transactions can be executed on the state machine.
    #[serde(rename = "allowUnprotectedTxs", skip_serializing_if = "Option::is_none")]
    pub allow_unprotected_txs: Option<bool>,
}

impl EthermintPeriodEvmPeriodV1PeriodParams {
    pub fn new() -> EthermintPeriodEvmPeriodV1PeriodParams {
        EthermintPeriodEvmPeriodV1PeriodParams {
            evm_denom: None,
            enable_create: None,
            enable_call: None,
            extra_eips: None,
            chain_config: None,
            allow_unprotected_txs: None,
        }
    }
}


