/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EthermintPeriodEvmPeriodV1PeriodQueryValidatorAccountResponse : QueryValidatorAccountResponse is the response type for the Query/ValidatorAccount RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EthermintPeriodEvmPeriodV1PeriodQueryValidatorAccountResponse {
    /// account_address is the cosmos address of the account in bech32 format.
    #[serde(rename = "accountAddress", skip_serializing_if = "Option::is_none")]
    pub account_address: Option<String>,
    /// sequence is the account's sequence number.
    #[serde(rename = "sequence", skip_serializing_if = "Option::is_none")]
    pub sequence: Option<String>,
    #[serde(rename = "accountNumber", skip_serializing_if = "Option::is_none")]
    pub account_number: Option<String>,
}

impl EthermintPeriodEvmPeriodV1PeriodQueryValidatorAccountResponse {
    /// QueryValidatorAccountResponse is the response type for the Query/ValidatorAccount RPC method.
    pub fn new() -> EthermintPeriodEvmPeriodV1PeriodQueryValidatorAccountResponse {
        EthermintPeriodEvmPeriodV1PeriodQueryValidatorAccountResponse {
            account_address: None,
            sequence: None,
            account_number: None,
        }
    }
}


