/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EthermintPeriodFeemarketPeriodV1PeriodQueryBlockGasResponse : QueryBlockGasResponse returns block gas used for a given height.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EthermintPeriodFeemarketPeriodV1PeriodQueryBlockGasResponse {
    #[serde(rename = "gas", skip_serializing_if = "Option::is_none")]
    pub gas: Option<String>,
}

impl EthermintPeriodFeemarketPeriodV1PeriodQueryBlockGasResponse {
    /// QueryBlockGasResponse returns block gas used for a given height.
    pub fn new() -> EthermintPeriodFeemarketPeriodV1PeriodQueryBlockGasResponse {
        EthermintPeriodFeemarketPeriodV1PeriodQueryBlockGasResponse {
            gas: None,
        }
    }
}


