/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EthermintPeriodEvmPeriodV1PeriodQueryAccountResponse : QueryAccountResponse is the response type for the Query/Account RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EthermintPeriodEvmPeriodV1PeriodQueryAccountResponse {
    /// balance is the balance of the EVM denomination.
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<String>,
    /// code_hash is the hex-formatted code bytes from the EOA.
    #[serde(rename = "codeHash", skip_serializing_if = "Option::is_none")]
    pub code_hash: Option<String>,
    /// nonce is the account's sequence number.
    #[serde(rename = "nonce", skip_serializing_if = "Option::is_none")]
    pub nonce: Option<String>,
}

impl EthermintPeriodEvmPeriodV1PeriodQueryAccountResponse {
    /// QueryAccountResponse is the response type for the Query/Account RPC method.
    pub fn new() -> EthermintPeriodEvmPeriodV1PeriodQueryAccountResponse {
        EthermintPeriodEvmPeriodV1PeriodQueryAccountResponse {
            balance: None,
            code_hash: None,
            nonce: None,
        }
    }
}


