/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EthermintPeriodEvmPeriodV1PeriodQueryStorageResponse : QueryStorageResponse is the response type for the Query/Storage RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EthermintPeriodEvmPeriodV1PeriodQueryStorageResponse {
    /// value defines the storage state value hash associated with the given key.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl EthermintPeriodEvmPeriodV1PeriodQueryStorageResponse {
    /// QueryStorageResponse is the response type for the Query/Storage RPC method.
    pub fn new() -> EthermintPeriodEvmPeriodV1PeriodQueryStorageResponse {
        EthermintPeriodEvmPeriodV1PeriodQueryStorageResponse {
            value: None,
        }
    }
}


