/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EthermintPeriodEvmPeriodV1PeriodMsgEthereumTx : MsgEthereumTx encapsulates an Ethereum transaction as an SDK message.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EthermintPeriodEvmPeriodV1PeriodMsgEthereumTx {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<crate::models::GooglePeriodProtobufPeriodAny>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<f64>,
    #[serde(rename = "hash", skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,
}

impl EthermintPeriodEvmPeriodV1PeriodMsgEthereumTx {
    /// MsgEthereumTx encapsulates an Ethereum transaction as an SDK message.
    pub fn new() -> EthermintPeriodEvmPeriodV1PeriodMsgEthereumTx {
        EthermintPeriodEvmPeriodV1PeriodMsgEthereumTx {
            data: None,
            size: None,
            hash: None,
            from: None,
        }
    }
}


