/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EthermintPeriodEvmPeriodV1PeriodMsgEthereumTxResponse : MsgEthereumTxResponse defines the Msg/EthereumTx response type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EthermintPeriodEvmPeriodV1PeriodMsgEthereumTxResponse {
    #[serde(rename = "hash", skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
    /// logs contains the transaction hash and the proto-compatible ethereum logs.
    #[serde(rename = "logs", skip_serializing_if = "Option::is_none")]
    pub logs: Option<Vec<crate::models::EthermintPeriodEvmPeriodV1PeriodLog>>,
    #[serde(rename = "ret", skip_serializing_if = "Option::is_none")]
    pub ret: Option<String>,
    #[serde(rename = "vmError", skip_serializing_if = "Option::is_none")]
    pub vm_error: Option<String>,
    #[serde(rename = "gasUsed", skip_serializing_if = "Option::is_none")]
    pub gas_used: Option<String>,
}

impl EthermintPeriodEvmPeriodV1PeriodMsgEthereumTxResponse {
    /// MsgEthereumTxResponse defines the Msg/EthereumTx response type.
    pub fn new() -> EthermintPeriodEvmPeriodV1PeriodMsgEthereumTxResponse {
        EthermintPeriodEvmPeriodV1PeriodMsgEthereumTxResponse {
            hash: None,
            logs: None,
            ret: None,
            vm_error: None,
            gas_used: None,
        }
    }
}


