/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EthermintPeriodEvmPeriodV1PeriodQueryCosmosAccountResponse : QueryCosmosAccountResponse is the response type for the Query/CosmosAccount RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EthermintPeriodEvmPeriodV1PeriodQueryCosmosAccountResponse {
    /// cosmos_address is the cosmos address of the account.
    #[serde(rename = "cosmosAddress", skip_serializing_if = "Option::is_none")]
    pub cosmos_address: Option<String>,
    /// sequence is the account's sequence number.
    #[serde(rename = "sequence", skip_serializing_if = "Option::is_none")]
    pub sequence: Option<String>,
    #[serde(rename = "accountNumber", skip_serializing_if = "Option::is_none")]
    pub account_number: Option<String>,
}

impl EthermintPeriodEvmPeriodV1PeriodQueryCosmosAccountResponse {
    /// QueryCosmosAccountResponse is the response type for the Query/CosmosAccount RPC method.
    pub fn new() -> EthermintPeriodEvmPeriodV1PeriodQueryCosmosAccountResponse {
        EthermintPeriodEvmPeriodV1PeriodQueryCosmosAccountResponse {
            cosmos_address: None,
            sequence: None,
            account_number: None,
        }
    }
}


