/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EthermintPeriodEvmPeriodV1PeriodChainConfig : ChainConfig defines the Ethereum ChainConfig parameters using *sdk.Int values instead of *big.Int.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EthermintPeriodEvmPeriodV1PeriodChainConfig {
    #[serde(rename = "homesteadBlock", skip_serializing_if = "Option::is_none")]
    pub homestead_block: Option<String>,
    #[serde(rename = "daoForkBlock", skip_serializing_if = "Option::is_none")]
    pub dao_fork_block: Option<String>,
    #[serde(rename = "daoForkSupport", skip_serializing_if = "Option::is_none")]
    pub dao_fork_support: Option<bool>,
    #[serde(rename = "eip150Block", skip_serializing_if = "Option::is_none")]
    pub eip150_block: Option<String>,
    #[serde(rename = "eip150Hash", skip_serializing_if = "Option::is_none")]
    pub eip150_hash: Option<String>,
    #[serde(rename = "eip155Block", skip_serializing_if = "Option::is_none")]
    pub eip155_block: Option<String>,
    #[serde(rename = "eip158Block", skip_serializing_if = "Option::is_none")]
    pub eip158_block: Option<String>,
    #[serde(rename = "byzantiumBlock", skip_serializing_if = "Option::is_none")]
    pub byzantium_block: Option<String>,
    #[serde(rename = "constantinopleBlock", skip_serializing_if = "Option::is_none")]
    pub constantinople_block: Option<String>,
    #[serde(rename = "petersburgBlock", skip_serializing_if = "Option::is_none")]
    pub petersburg_block: Option<String>,
    #[serde(rename = "istanbulBlock", skip_serializing_if = "Option::is_none")]
    pub istanbul_block: Option<String>,
    #[serde(rename = "muirGlacierBlock", skip_serializing_if = "Option::is_none")]
    pub muir_glacier_block: Option<String>,
    #[serde(rename = "berlinBlock", skip_serializing_if = "Option::is_none")]
    pub berlin_block: Option<String>,
    #[serde(rename = "londonBlock", skip_serializing_if = "Option::is_none")]
    pub london_block: Option<String>,
    #[serde(rename = "arrowGlacierBlock", skip_serializing_if = "Option::is_none")]
    pub arrow_glacier_block: Option<String>,
    #[serde(rename = "grayGlacierBlock", skip_serializing_if = "Option::is_none")]
    pub gray_glacier_block: Option<String>,
    #[serde(rename = "mergeNetsplitBlock", skip_serializing_if = "Option::is_none")]
    pub merge_netsplit_block: Option<String>,
    #[serde(rename = "shanghaiBlock", skip_serializing_if = "Option::is_none")]
    pub shanghai_block: Option<String>,
    #[serde(rename = "cancunBlock", skip_serializing_if = "Option::is_none")]
    pub cancun_block: Option<String>,
}

impl EthermintPeriodEvmPeriodV1PeriodChainConfig {
    /// ChainConfig defines the Ethereum ChainConfig parameters using *sdk.Int values instead of *big.Int.
    pub fn new() -> EthermintPeriodEvmPeriodV1PeriodChainConfig {
        EthermintPeriodEvmPeriodV1PeriodChainConfig {
            homestead_block: None,
            dao_fork_block: None,
            dao_fork_support: None,
            eip150_block: None,
            eip150_hash: None,
            eip155_block: None,
            eip158_block: None,
            byzantium_block: None,
            constantinople_block: None,
            petersburg_block: None,
            istanbul_block: None,
            muir_glacier_block: None,
            berlin_block: None,
            london_block: None,
            arrow_glacier_block: None,
            gray_glacier_block: None,
            merge_netsplit_block: None,
            shanghai_block: None,
            cancun_block: None,
        }
    }
}


