/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EthermintPeriodEvmPeriodV1PeriodQueryBalanceResponse : QueryBalanceResponse is the response type for the Query/Balance RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EthermintPeriodEvmPeriodV1PeriodQueryBalanceResponse {
    /// balance is the balance of the EVM denomination.
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<String>,
}

impl EthermintPeriodEvmPeriodV1PeriodQueryBalanceResponse {
    /// QueryBalanceResponse is the response type for the Query/Balance RPC method.
    pub fn new() -> EthermintPeriodEvmPeriodV1PeriodQueryBalanceResponse {
        EthermintPeriodEvmPeriodV1PeriodQueryBalanceResponse {
            balance: None,
        }
    }
}


