/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EthermintPeriodEvmPeriodV1PeriodQueryTraceTxResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<String>,
}

impl EthermintPeriodEvmPeriodV1PeriodQueryTraceTxResponse {
    pub fn new() -> EthermintPeriodEvmPeriodV1PeriodQueryTraceTxResponse {
        EthermintPeriodEvmPeriodV1PeriodQueryTraceTxResponse {
            data: None,
        }
    }
}


