/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EthermintPeriodFeemarketPeriodV1PeriodQueryBaseFeeResponse : QueryBaseFeeResponse returns the EIP1559 base fee.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EthermintPeriodFeemarketPeriodV1PeriodQueryBaseFeeResponse {
    #[serde(rename = "baseFee", skip_serializing_if = "Option::is_none")]
    pub base_fee: Option<String>,
}

impl EthermintPeriodFeemarketPeriodV1PeriodQueryBaseFeeResponse {
    /// QueryBaseFeeResponse returns the EIP1559 base fee.
    pub fn new() -> EthermintPeriodFeemarketPeriodV1PeriodQueryBaseFeeResponse {
        EthermintPeriodFeemarketPeriodV1PeriodQueryBaseFeeResponse {
            base_fee: None,
        }
    }
}


