/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EvmosPeriodErc20PeriodV1PeriodOwner : Owner enumerates the ownership of a ERC20 contract.   - OWNER_UNSPECIFIED: OWNER_UNSPECIFIED defines an invalid/undefined owner.  - OWNER_MODULE: OWNER_MODULE - erc20 is owned by the erc20 module account.  - OWNER_EXTERNAL: OWNER_EXTERNAL - erc20 is owned by an external account.

/// Owner enumerates the ownership of a ERC20 contract.   - OWNER_UNSPECIFIED: OWNER_UNSPECIFIED defines an invalid/undefined owner.  - OWNER_MODULE: OWNER_MODULE - erc20 is owned by the erc20 module account.  - OWNER_EXTERNAL: OWNER_EXTERNAL - erc20 is owned by an external account.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EvmosPeriodErc20PeriodV1PeriodOwner {
    #[serde(rename = "OWNER_UNSPECIFIED")]
    Unspecified,
    #[serde(rename = "OWNER_MODULE")]
    Module,
    #[serde(rename = "OWNER_EXTERNAL")]
    External,

}

impl ToString for EvmosPeriodErc20PeriodV1PeriodOwner {
    fn to_string(&self) -> String {
        match self {
            Self::Unspecified => String::from("OWNER_UNSPECIFIED"),
            Self::Module => String::from("OWNER_MODULE"),
            Self::External => String::from("OWNER_EXTERNAL"),
        }
    }
}

impl Default for EvmosPeriodErc20PeriodV1PeriodOwner {
    fn default() -> EvmosPeriodErc20PeriodV1PeriodOwner {
        Self::Unspecified
    }
}




