/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EvmosPeriodEpochsPeriodV1PeriodEpochInfo : EpochInfo defines the message interface containing the relevant informations about an epoch.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EvmosPeriodEpochsPeriodV1PeriodEpochInfo {
    #[serde(rename = "identifier", skip_serializing_if = "Option::is_none")]
    pub identifier: Option<String>,
    #[serde(rename = "startTime", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<String>,
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<String>,
    #[serde(rename = "currentEpoch", skip_serializing_if = "Option::is_none")]
    pub current_epoch: Option<String>,
    #[serde(rename = "currentEpochStartTime", skip_serializing_if = "Option::is_none")]
    pub current_epoch_start_time: Option<String>,
    #[serde(rename = "epochCountingStarted", skip_serializing_if = "Option::is_none")]
    pub epoch_counting_started: Option<bool>,
    #[serde(rename = "currentEpochStartHeight", skip_serializing_if = "Option::is_none")]
    pub current_epoch_start_height: Option<String>,
}

impl EvmosPeriodEpochsPeriodV1PeriodEpochInfo {
    /// EpochInfo defines the message interface containing the relevant informations about an epoch.
    pub fn new() -> EvmosPeriodEpochsPeriodV1PeriodEpochInfo {
        EvmosPeriodEpochsPeriodV1PeriodEpochInfo {
            identifier: None,
            start_time: None,
            duration: None,
            current_epoch: None,
            current_epoch_start_time: None,
            epoch_counting_started: None,
            current_epoch_start_height: None,
        }
    }
}


