/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EvmosPeriodEpochsPeriodV1PeriodQueryCurrentEpochResponse : QueryCurrentEpochResponse is the response type for the Query/EpochInfos RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EvmosPeriodEpochsPeriodV1PeriodQueryCurrentEpochResponse {
    #[serde(rename = "currentEpoch", skip_serializing_if = "Option::is_none")]
    pub current_epoch: Option<String>,
}

impl EvmosPeriodEpochsPeriodV1PeriodQueryCurrentEpochResponse {
    /// QueryCurrentEpochResponse is the response type for the Query/EpochInfos RPC method.
    pub fn new() -> EvmosPeriodEpochsPeriodV1PeriodQueryCurrentEpochResponse {
        EvmosPeriodEpochsPeriodV1PeriodQueryCurrentEpochResponse {
            current_epoch: None,
        }
    }
}


