/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EvmosPeriodErc20PeriodV1PeriodQueryTokenPairsResponse : QueryTokenPairsResponse is the response type for the Query/TokenPairs RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EvmosPeriodErc20PeriodV1PeriodQueryTokenPairsResponse {
    #[serde(rename = "tokenPairs", skip_serializing_if = "Option::is_none")]
    pub token_pairs: Option<Vec<crate::models::EvmosPeriodErc20PeriodV1PeriodTokenPair>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl EvmosPeriodErc20PeriodV1PeriodQueryTokenPairsResponse {
    /// QueryTokenPairsResponse is the response type for the Query/TokenPairs RPC method.
    pub fn new() -> EvmosPeriodErc20PeriodV1PeriodQueryTokenPairsResponse {
        EvmosPeriodErc20PeriodV1PeriodQueryTokenPairsResponse {
            token_pairs: None,
            pagination: None,
        }
    }
}


