/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EvmosPeriodEpochsPeriodV1PeriodQueryEpochsInfoResponse : QueryEpochsInfoResponse is the response type for the Query/EpochInfos RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EvmosPeriodEpochsPeriodV1PeriodQueryEpochsInfoResponse {
    #[serde(rename = "epochs", skip_serializing_if = "Option::is_none")]
    pub epochs: Option<Vec<crate::models::EvmosPeriodEpochsPeriodV1PeriodEpochInfo>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::CosmosPeriodBasePeriodQueryPeriodV1beta1PeriodPageResponse>>,
}

impl EvmosPeriodEpochsPeriodV1PeriodQueryEpochsInfoResponse {
    /// QueryEpochsInfoResponse is the response type for the Query/EpochInfos RPC method.
    pub fn new() -> EvmosPeriodEpochsPeriodV1PeriodQueryEpochsInfoResponse {
        EvmosPeriodEpochsPeriodV1PeriodQueryEpochsInfoResponse {
            epochs: None,
            pagination: None,
        }
    }
}


