/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EvmosPeriodErc20PeriodV1PeriodQueryTokenPairResponse : QueryTokenPairResponse is the response type for the Query/TokenPair RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EvmosPeriodErc20PeriodV1PeriodQueryTokenPairResponse {
    #[serde(rename = "tokenPair", skip_serializing_if = "Option::is_none")]
    pub token_pair: Option<Box<crate::models::EvmosPeriodErc20PeriodV1PeriodTokenPair>>,
}

impl EvmosPeriodErc20PeriodV1PeriodQueryTokenPairResponse {
    /// QueryTokenPairResponse is the response type for the Query/TokenPair RPC method.
    pub fn new() -> EvmosPeriodErc20PeriodV1PeriodQueryTokenPairResponse {
        EvmosPeriodErc20PeriodV1PeriodQueryTokenPairResponse {
            token_pair: None,
        }
    }
}


