/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EvmosPeriodErc20PeriodV1PeriodParams {
    /// enable_erc20 is the parameter to enable the conversion of Cosmos coins <--> ERC20 tokens.
    #[serde(rename = "enableErc20", skip_serializing_if = "Option::is_none")]
    pub enable_erc20: Option<bool>,
    /// enable_evm_hook is the parameter to enable the EVM hook that converts an ERC20 token to a Cosmos Coin by transferring the Tokens through a MsgEthereumTx to the ModuleAddress Ethereum address.
    #[serde(rename = "enableEvmHook", skip_serializing_if = "Option::is_none")]
    pub enable_evm_hook: Option<bool>,
}

impl EvmosPeriodErc20PeriodV1PeriodParams {
    pub fn new() -> EvmosPeriodErc20PeriodV1PeriodParams {
        EvmosPeriodErc20PeriodV1PeriodParams {
            enable_erc20: None,
            enable_evm_hook: None,
        }
    }
}


