/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GooglePeriodRpcPeriodStatus {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<Vec<crate::models::GooglePeriodProtobufPeriodAny>>,
}

impl GooglePeriodRpcPeriodStatus {
    pub fn new() -> GooglePeriodRpcPeriodStatus {
        GooglePeriodRpcPeriodStatus {
            code: None,
            message: None,
            details: None,
        }
    }
}


