/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HaqqPeriodCoinomicsPeriodV1PeriodQueryEraResponse {
    #[serde(rename = "era", skip_serializing_if = "Option::is_none")]
    pub era: Option<String>,
}

impl HaqqPeriodCoinomicsPeriodV1PeriodQueryEraResponse {
    pub fn new() -> HaqqPeriodCoinomicsPeriodV1PeriodQueryEraResponse {
        HaqqPeriodCoinomicsPeriodV1PeriodQueryEraResponse {
            era: None,
        }
    }
}


