/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// HaqqPeriodCoinomicsPeriodV1PeriodParams : Params holds parameters for the coinomics module.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HaqqPeriodCoinomicsPeriodV1PeriodParams {
    #[serde(rename = "mintDenom", skip_serializing_if = "Option::is_none")]
    pub mint_denom: Option<String>,
    #[serde(rename = "blocksPerEra", skip_serializing_if = "Option::is_none")]
    pub blocks_per_era: Option<String>,
    #[serde(rename = "enableCoinomics", skip_serializing_if = "Option::is_none")]
    pub enable_coinomics: Option<bool>,
}

impl HaqqPeriodCoinomicsPeriodV1PeriodParams {
    /// Params holds parameters for the coinomics module.
    pub fn new() -> HaqqPeriodCoinomicsPeriodV1PeriodParams {
        HaqqPeriodCoinomicsPeriodV1PeriodParams {
            mint_denom: None,
            blocks_per_era: None,
            enable_coinomics: None,
        }
    }
}


