/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// HaqqPeriodVestingPeriodV1PeriodQueryBalancesResponse : QueryBalancesResponse is the response type for the Query/Balances RPC method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HaqqPeriodVestingPeriodV1PeriodQueryBalancesResponse {
    #[serde(rename = "locked", skip_serializing_if = "Option::is_none")]
    pub locked: Option<Vec<crate::models::CosmosPeriodBasePeriodV1beta1PeriodCoin>>,
    #[serde(rename = "unvested", skip_serializing_if = "Option::is_none")]
    pub unvested: Option<Vec<crate::models::CosmosPeriodBasePeriodV1beta1PeriodCoin>>,
    #[serde(rename = "vested", skip_serializing_if = "Option::is_none")]
    pub vested: Option<Vec<crate::models::CosmosPeriodBasePeriodV1beta1PeriodCoin>>,
}

impl HaqqPeriodVestingPeriodV1PeriodQueryBalancesResponse {
    /// QueryBalancesResponse is the response type for the Query/Balances RPC method.
    pub fn new() -> HaqqPeriodVestingPeriodV1PeriodQueryBalancesResponse {
        HaqqPeriodVestingPeriodV1PeriodQueryBalancesResponse {
            locked: None,
            unvested: None,
            vested: None,
        }
    }
}


