/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TendermintPeriodAbciPeriodEvidenceType {
    #[serde(rename = "UNKNOWN")]
    Unknown,
    #[serde(rename = "DUPLICATE_VOTE")]
    DuplicateVote,
    #[serde(rename = "LIGHT_CLIENT_ATTACK")]
    LightClientAttack,

}

impl ToString for TendermintPeriodAbciPeriodEvidenceType {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("UNKNOWN"),
            Self::DuplicateVote => String::from("DUPLICATE_VOTE"),
            Self::LightClientAttack => String::from("LIGHT_CLIENT_ATTACK"),
        }
    }
}

impl Default for TendermintPeriodAbciPeriodEvidenceType {
    fn default() -> TendermintPeriodAbciPeriodEvidenceType {
        Self::Unknown
    }
}




