/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodTypesPeriodValidator {
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "pubKey", skip_serializing_if = "Option::is_none")]
    pub pub_key: Option<Box<crate::models::TendermintPeriodCryptoPeriodPublicKey>>,
    #[serde(rename = "votingPower", skip_serializing_if = "Option::is_none")]
    pub voting_power: Option<String>,
    #[serde(rename = "proposerPriority", skip_serializing_if = "Option::is_none")]
    pub proposer_priority: Option<String>,
}

impl TendermintPeriodTypesPeriodValidator {
    pub fn new() -> TendermintPeriodTypesPeriodValidator {
        TendermintPeriodTypesPeriodValidator {
            address: None,
            pub_key: None,
            voting_power: None,
            proposer_priority: None,
        }
    }
}


