/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodAbciPeriodSnapshot {
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<String>,
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<i64>,
    #[serde(rename = "chunks", skip_serializing_if = "Option::is_none")]
    pub chunks: Option<i64>,
    #[serde(rename = "hash", skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<String>,
}

impl TendermintPeriodAbciPeriodSnapshot {
    pub fn new() -> TendermintPeriodAbciPeriodSnapshot {
        TendermintPeriodAbciPeriodSnapshot {
            height: None,
            format: None,
            chunks: None,
            hash: None,
            metadata: None,
        }
    }
}


