/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodAbciPeriodResponseBeginBlock {
    #[serde(rename = "events", skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<crate::models::TendermintPeriodAbciPeriodEvent>>,
}

impl TendermintPeriodAbciPeriodResponseBeginBlock {
    pub fn new() -> TendermintPeriodAbciPeriodResponseBeginBlock {
        TendermintPeriodAbciPeriodResponseBeginBlock {
            events: None,
        }
    }
}


