/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodAbciPeriodResponseCheckTx {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i64>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<String>,
    #[serde(rename = "log", skip_serializing_if = "Option::is_none")]
    pub log: Option<String>,
    #[serde(rename = "info", skip_serializing_if = "Option::is_none")]
    pub info: Option<String>,
    #[serde(rename = "gas_wanted", skip_serializing_if = "Option::is_none")]
    pub gas_wanted: Option<String>,
    #[serde(rename = "gas_used", skip_serializing_if = "Option::is_none")]
    pub gas_used: Option<String>,
    #[serde(rename = "events", skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<crate::models::TendermintPeriodAbciPeriodEvent>>,
    #[serde(rename = "codespace", skip_serializing_if = "Option::is_none")]
    pub codespace: Option<String>,
    #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
    pub sender: Option<String>,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<String>,
    /// mempool_error is set by CometBFT. ABCI applictions creating a ResponseCheckTX should not set mempool_error.
    #[serde(rename = "mempoolError", skip_serializing_if = "Option::is_none")]
    pub mempool_error: Option<String>,
}

impl TendermintPeriodAbciPeriodResponseCheckTx {
    pub fn new() -> TendermintPeriodAbciPeriodResponseCheckTx {
        TendermintPeriodAbciPeriodResponseCheckTx {
            code: None,
            data: None,
            log: None,
            info: None,
            gas_wanted: None,
            gas_used: None,
            events: None,
            codespace: None,
            sender: None,
            priority: None,
            mempool_error: None,
        }
    }
}


