/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TendermintPeriodVersionPeriodConsensus : Consensus captures the consensus rules for processing a block in the blockchain, including all blockchain data structures and the rules of the application's state transition machine.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodVersionPeriodConsensus {
    #[serde(rename = "block", skip_serializing_if = "Option::is_none")]
    pub block: Option<String>,
    #[serde(rename = "app", skip_serializing_if = "Option::is_none")]
    pub app: Option<String>,
}

impl TendermintPeriodVersionPeriodConsensus {
    /// Consensus captures the consensus rules for processing a block in the blockchain, including all blockchain data structures and the rules of the application's state transition machine.
    pub fn new() -> TendermintPeriodVersionPeriodConsensus {
        TendermintPeriodVersionPeriodConsensus {
            block: None,
            app: None,
        }
    }
}


