/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TendermintPeriodTypesPeriodCommitSig : CommitSig is a part of the Vote included in a Commit.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodTypesPeriodCommitSig {
    #[serde(rename = "blockIdFlag", skip_serializing_if = "Option::is_none")]
    pub block_id_flag: Option<crate::models::TendermintPeriodTypesPeriodBlockIdFlag>,
    #[serde(rename = "validatorAddress", skip_serializing_if = "Option::is_none")]
    pub validator_address: Option<String>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>,
}

impl TendermintPeriodTypesPeriodCommitSig {
    /// CommitSig is a part of the Vote included in a Commit.
    pub fn new() -> TendermintPeriodTypesPeriodCommitSig {
        TendermintPeriodTypesPeriodCommitSig {
            block_id_flag: None,
            validator_address: None,
            timestamp: None,
            signature: None,
        }
    }
}


