/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodAbciPeriodConsensusParams {
    #[serde(rename = "block", skip_serializing_if = "Option::is_none")]
    pub block: Option<Box<crate::models::TendermintPeriodAbciPeriodBlockParams>>,
    #[serde(rename = "evidence", skip_serializing_if = "Option::is_none")]
    pub evidence: Option<Box<crate::models::TendermintPeriodTypesPeriodEvidenceParams>>,
    #[serde(rename = "validator", skip_serializing_if = "Option::is_none")]
    pub validator: Option<Box<crate::models::TendermintPeriodTypesPeriodValidatorParams>>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<Box<crate::models::TendermintPeriodTypesPeriodVersionParams>>,
}

impl TendermintPeriodAbciPeriodConsensusParams {
    pub fn new() -> TendermintPeriodAbciPeriodConsensusParams {
        TendermintPeriodAbciPeriodConsensusParams {
            block: None,
            evidence: None,
            validator: None,
            version: None,
        }
    }
}


