/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TendermintPeriodAbciPeriodBlockParams : BlockParams contains limits on the block size.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodAbciPeriodBlockParams {
    #[serde(rename = "maxBytes", skip_serializing_if = "Option::is_none")]
    pub max_bytes: Option<String>,
    #[serde(rename = "maxGas", skip_serializing_if = "Option::is_none")]
    pub max_gas: Option<String>,
}

impl TendermintPeriodAbciPeriodBlockParams {
    /// BlockParams contains limits on the block size.
    pub fn new() -> TendermintPeriodAbciPeriodBlockParams {
        TendermintPeriodAbciPeriodBlockParams {
            max_bytes: None,
            max_gas: None,
        }
    }
}


