/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodAbciPeriodVoteInfo {
    #[serde(rename = "validator", skip_serializing_if = "Option::is_none")]
    pub validator: Option<Box<crate::models::TendermintPeriodAbciPeriodValidator>>,
    #[serde(rename = "signedLastBlock", skip_serializing_if = "Option::is_none")]
    pub signed_last_block: Option<bool>,
}

impl TendermintPeriodAbciPeriodVoteInfo {
    pub fn new() -> TendermintPeriodAbciPeriodVoteInfo {
        TendermintPeriodAbciPeriodVoteInfo {
            validator: None,
            signed_last_block: None,
        }
    }
}


