/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TendermintPeriodTypesPeriodDuplicateVoteEvidence : DuplicateVoteEvidence contains evidence of a validator signed two conflicting votes.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodTypesPeriodDuplicateVoteEvidence {
    #[serde(rename = "voteA", skip_serializing_if = "Option::is_none")]
    pub vote_a: Option<Box<crate::models::TendermintPeriodTypesPeriodVote>>,
    #[serde(rename = "voteB", skip_serializing_if = "Option::is_none")]
    pub vote_b: Option<Box<crate::models::TendermintPeriodTypesPeriodVote>>,
    #[serde(rename = "totalVotingPower", skip_serializing_if = "Option::is_none")]
    pub total_voting_power: Option<String>,
    #[serde(rename = "validatorPower", skip_serializing_if = "Option::is_none")]
    pub validator_power: Option<String>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
}

impl TendermintPeriodTypesPeriodDuplicateVoteEvidence {
    /// DuplicateVoteEvidence contains evidence of a validator signed two conflicting votes.
    pub fn new() -> TendermintPeriodTypesPeriodDuplicateVoteEvidence {
        TendermintPeriodTypesPeriodDuplicateVoteEvidence {
            vote_a: None,
            vote_b: None,
            total_voting_power: None,
            validator_power: None,
            timestamp: None,
        }
    }
}


