/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TendermintPeriodAbciPeriodCheckTxType {
    #[serde(rename = "NEW")]
    New,
    #[serde(rename = "RECHECK")]
    Recheck,

}

impl ToString for TendermintPeriodAbciPeriodCheckTxType {
    fn to_string(&self) -> String {
        match self {
            Self::New => String::from("NEW"),
            Self::Recheck => String::from("RECHECK"),
        }
    }
}

impl Default for TendermintPeriodAbciPeriodCheckTxType {
    fn default() -> TendermintPeriodAbciPeriodCheckTxType {
        Self::New
    }
}




