/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodTypesPeriodValidatorSet {
    #[serde(rename = "validators", skip_serializing_if = "Option::is_none")]
    pub validators: Option<Vec<crate::models::TendermintPeriodTypesPeriodValidator>>,
    #[serde(rename = "proposer", skip_serializing_if = "Option::is_none")]
    pub proposer: Option<Box<crate::models::TendermintPeriodTypesPeriodValidator>>,
    #[serde(rename = "totalVotingPower", skip_serializing_if = "Option::is_none")]
    pub total_voting_power: Option<String>,
}

impl TendermintPeriodTypesPeriodValidatorSet {
    pub fn new() -> TendermintPeriodTypesPeriodValidatorSet {
        TendermintPeriodTypesPeriodValidatorSet {
            validators: None,
            proposer: None,
            total_voting_power: None,
        }
    }
}


