/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodTypesPeriodLightBlock {
    #[serde(rename = "signedHeader", skip_serializing_if = "Option::is_none")]
    pub signed_header: Option<Box<crate::models::TendermintPeriodTypesPeriodSignedHeader>>,
    #[serde(rename = "validatorSet", skip_serializing_if = "Option::is_none")]
    pub validator_set: Option<Box<crate::models::TendermintPeriodTypesPeriodValidatorSet>>,
}

impl TendermintPeriodTypesPeriodLightBlock {
    pub fn new() -> TendermintPeriodTypesPeriodLightBlock {
        TendermintPeriodTypesPeriodLightBlock {
            signed_header: None,
            validator_set: None,
        }
    }
}


