/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodP2pPeriodProtocolVersion {
    #[serde(rename = "p2p", skip_serializing_if = "Option::is_none")]
    pub p2p: Option<String>,
    #[serde(rename = "block", skip_serializing_if = "Option::is_none")]
    pub block: Option<String>,
    #[serde(rename = "app", skip_serializing_if = "Option::is_none")]
    pub app: Option<String>,
}

impl TendermintPeriodP2pPeriodProtocolVersion {
    pub fn new() -> TendermintPeriodP2pPeriodProtocolVersion {
        TendermintPeriodP2pPeriodProtocolVersion {
            p2p: None,
            block: None,
            app: None,
        }
    }
}


