/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodP2pPeriodDefaultNodeInfo {
    #[serde(rename = "protocolVersion", skip_serializing_if = "Option::is_none")]
    pub protocol_version: Option<Box<crate::models::TendermintPeriodP2pPeriodProtocolVersion>>,
    #[serde(rename = "defaultNodeId", skip_serializing_if = "Option::is_none")]
    pub default_node_id: Option<String>,
    #[serde(rename = "listenAddr", skip_serializing_if = "Option::is_none")]
    pub listen_addr: Option<String>,
    #[serde(rename = "network", skip_serializing_if = "Option::is_none")]
    pub network: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "channels", skip_serializing_if = "Option::is_none")]
    pub channels: Option<String>,
    #[serde(rename = "moniker", skip_serializing_if = "Option::is_none")]
    pub moniker: Option<String>,
    #[serde(rename = "other", skip_serializing_if = "Option::is_none")]
    pub other: Option<Box<crate::models::TendermintPeriodP2pPeriodDefaultNodeInfoOther>>,
}

impl TendermintPeriodP2pPeriodDefaultNodeInfo {
    pub fn new() -> TendermintPeriodP2pPeriodDefaultNodeInfo {
        TendermintPeriodP2pPeriodDefaultNodeInfo {
            protocol_version: None,
            default_node_id: None,
            listen_addr: None,
            network: None,
            version: None,
            channels: None,
            moniker: None,
            other: None,
        }
    }
}


