/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodAbciPeriodResponseLoadSnapshotChunk {
    #[serde(rename = "chunk", skip_serializing_if = "Option::is_none")]
    pub chunk: Option<String>,
}

impl TendermintPeriodAbciPeriodResponseLoadSnapshotChunk {
    pub fn new() -> TendermintPeriodAbciPeriodResponseLoadSnapshotChunk {
        TendermintPeriodAbciPeriodResponseLoadSnapshotChunk {
            chunk: None,
        }
    }
}


