/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodAbciPeriodResponseApplySnapshotChunk {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<crate::models::TendermintPeriodAbciPeriodResponseApplySnapshotChunkPeriodResult>,
    #[serde(rename = "refetchChunks", skip_serializing_if = "Option::is_none")]
    pub refetch_chunks: Option<Vec<i64>>,
    #[serde(rename = "rejectSenders", skip_serializing_if = "Option::is_none")]
    pub reject_senders: Option<Vec<String>>,
}

impl TendermintPeriodAbciPeriodResponseApplySnapshotChunk {
    pub fn new() -> TendermintPeriodAbciPeriodResponseApplySnapshotChunk {
        TendermintPeriodAbciPeriodResponseApplySnapshotChunk {
            result: None,
            refetch_chunks: None,
            reject_senders: None,
        }
    }
}


