/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TendermintPeriodTypesPeriodEvidenceParams : EvidenceParams determine how we handle evidence of malfeasance.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodTypesPeriodEvidenceParams {
    /// Max age of evidence, in blocks.  The basic formula for calculating this is: MaxAgeDuration / {average block time}.
    #[serde(rename = "maxAgeNumBlocks", skip_serializing_if = "Option::is_none")]
    pub max_age_num_blocks: Option<String>,
    /// Max age of evidence, in time.  It should correspond with an app's \"unbonding period\" or other similar mechanism for handling [Nothing-At-Stake attacks](https://github.com/ethereum/wiki/wiki/Proof-of-Stake-FAQ#what-is-the-nothing-at-stake-problem-and-how-can-it-be-fixed).
    #[serde(rename = "maxAgeDuration", skip_serializing_if = "Option::is_none")]
    pub max_age_duration: Option<String>,
    #[serde(rename = "maxBytes", skip_serializing_if = "Option::is_none")]
    pub max_bytes: Option<String>,
}

impl TendermintPeriodTypesPeriodEvidenceParams {
    /// EvidenceParams determine how we handle evidence of malfeasance.
    pub fn new() -> TendermintPeriodTypesPeriodEvidenceParams {
        TendermintPeriodTypesPeriodEvidenceParams {
            max_age_num_blocks: None,
            max_age_duration: None,
            max_bytes: None,
        }
    }
}


