/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodTypesPeriodEvidence {
    #[serde(rename = "duplicateVoteEvidence", skip_serializing_if = "Option::is_none")]
    pub duplicate_vote_evidence: Option<Box<crate::models::TendermintPeriodTypesPeriodDuplicateVoteEvidence>>,
    #[serde(rename = "lightClientAttackEvidence", skip_serializing_if = "Option::is_none")]
    pub light_client_attack_evidence: Option<Box<crate::models::TendermintPeriodTypesPeriodLightClientAttackEvidence>>,
}

impl TendermintPeriodTypesPeriodEvidence {
    pub fn new() -> TendermintPeriodTypesPeriodEvidence {
        TendermintPeriodTypesPeriodEvidence {
            duplicate_vote_evidence: None,
            light_client_attack_evidence: None,
        }
    }
}


