/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodAbciPeriodLastCommitInfo {
    #[serde(rename = "round", skip_serializing_if = "Option::is_none")]
    pub round: Option<i32>,
    #[serde(rename = "votes", skip_serializing_if = "Option::is_none")]
    pub votes: Option<Vec<crate::models::TendermintPeriodAbciPeriodVoteInfo>>,
}

impl TendermintPeriodAbciPeriodLastCommitInfo {
    pub fn new() -> TendermintPeriodAbciPeriodLastCommitInfo {
        TendermintPeriodAbciPeriodLastCommitInfo {
            round: None,
            votes: None,
        }
    }
}


