/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TendermintPeriodAbciPeriodEventAttribute : EventAttribute is a single key-value pair, associated with an event.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodAbciPeriodEventAttribute {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(rename = "index", skip_serializing_if = "Option::is_none")]
    pub index: Option<bool>,
}

impl TendermintPeriodAbciPeriodEventAttribute {
    /// EventAttribute is a single key-value pair, associated with an event.
    pub fn new() -> TendermintPeriodAbciPeriodEventAttribute {
        TendermintPeriodAbciPeriodEventAttribute {
            key: None,
            value: None,
            index: None,
        }
    }
}


