/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TendermintPeriodTypesPeriodSignedMsgType : SignedMsgType is a type of signed message in the consensus.   - SIGNED_MSG_TYPE_PREVOTE: Votes  - SIGNED_MSG_TYPE_PROPOSAL: Proposals

/// SignedMsgType is a type of signed message in the consensus.   - SIGNED_MSG_TYPE_PREVOTE: Votes  - SIGNED_MSG_TYPE_PROPOSAL: Proposals
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TendermintPeriodTypesPeriodSignedMsgType {
    #[serde(rename = "SIGNED_MSG_TYPE_UNKNOWN")]
    Unknown,
    #[serde(rename = "SIGNED_MSG_TYPE_PREVOTE")]
    Prevote,
    #[serde(rename = "SIGNED_MSG_TYPE_PRECOMMIT")]
    Precommit,
    #[serde(rename = "SIGNED_MSG_TYPE_PROPOSAL")]
    Proposal,

}

impl ToString for TendermintPeriodTypesPeriodSignedMsgType {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("SIGNED_MSG_TYPE_UNKNOWN"),
            Self::Prevote => String::from("SIGNED_MSG_TYPE_PREVOTE"),
            Self::Precommit => String::from("SIGNED_MSG_TYPE_PRECOMMIT"),
            Self::Proposal => String::from("SIGNED_MSG_TYPE_PROPOSAL"),
        }
    }
}

impl Default for TendermintPeriodTypesPeriodSignedMsgType {
    fn default() -> TendermintPeriodTypesPeriodSignedMsgType {
        Self::Unknown
    }
}




