/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodTypesPeriodSignedHeader {
    #[serde(rename = "header", skip_serializing_if = "Option::is_none")]
    pub header: Option<Box<crate::models::TendermintPeriodTypesPeriodHeader>>,
    #[serde(rename = "commit", skip_serializing_if = "Option::is_none")]
    pub commit: Option<Box<crate::models::TendermintPeriodTypesPeriodCommit>>,
}

impl TendermintPeriodTypesPeriodSignedHeader {
    pub fn new() -> TendermintPeriodTypesPeriodSignedHeader {
        TendermintPeriodTypesPeriodSignedHeader {
            header: None,
            commit: None,
        }
    }
}


