/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TendermintPeriodTypesPeriodValidatorParams : ValidatorParams restrict the public key types validators can use. NOTE: uses ABCI pubkey naming, not Amino names.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodTypesPeriodValidatorParams {
    #[serde(rename = "pubKeyTypes", skip_serializing_if = "Option::is_none")]
    pub pub_key_types: Option<Vec<String>>,
}

impl TendermintPeriodTypesPeriodValidatorParams {
    /// ValidatorParams restrict the public key types validators can use. NOTE: uses ABCI pubkey naming, not Amino names.
    pub fn new() -> TendermintPeriodTypesPeriodValidatorParams {
        TendermintPeriodTypesPeriodValidatorParams {
            pub_key_types: None,
        }
    }
}


