/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodTypesPeriodBlockId {
    #[serde(rename = "hash", skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
    #[serde(rename = "partSetHeader", skip_serializing_if = "Option::is_none")]
    pub part_set_header: Option<Box<crate::models::TendermintPeriodTypesPeriodPartSetHeader>>,
}

impl TendermintPeriodTypesPeriodBlockId {
    pub fn new() -> TendermintPeriodTypesPeriodBlockId {
        TendermintPeriodTypesPeriodBlockId {
            hash: None,
            part_set_header: None,
        }
    }
}


