/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TendermintPeriodTypesPeriodVersionParams : VersionParams contains the ABCI application version.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodTypesPeriodVersionParams {
    #[serde(rename = "appVersion", skip_serializing_if = "Option::is_none")]
    pub app_version: Option<String>,
}

impl TendermintPeriodTypesPeriodVersionParams {
    /// VersionParams contains the ABCI application version.
    pub fn new() -> TendermintPeriodTypesPeriodVersionParams {
        TendermintPeriodTypesPeriodVersionParams {
            app_version: None,
        }
    }
}


