/*
 * cosmos/app/v1alpha1/module.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintPeriodAbciPeriodResponseOfferSnapshot {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<crate::models::TendermintPeriodAbciPeriodResponseOfferSnapshotPeriodResult>,
}

impl TendermintPeriodAbciPeriodResponseOfferSnapshot {
    pub fn new() -> TendermintPeriodAbciPeriodResponseOfferSnapshot {
        TendermintPeriodAbciPeriodResponseOfferSnapshot {
            result: None,
        }
    }
}


